package com.cuize.task.dao.order.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderDetailPackdtlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public OrderDetailPackdtlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdIsNull() {
            addCriterion("order_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdIsNotNull() {
            addCriterion("order_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdEqualTo(Integer value) {
            addCriterion("order_detail_id =", value, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdNotEqualTo(Integer value) {
            addCriterion("order_detail_id <>", value, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdGreaterThan(Integer value) {
            addCriterion("order_detail_id >", value, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_detail_id >=", value, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdLessThan(Integer value) {
            addCriterion("order_detail_id <", value, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_detail_id <=", value, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdIn(List<Integer> values) {
            addCriterion("order_detail_id in", values, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdNotIn(List<Integer> values) {
            addCriterion("order_detail_id not in", values, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdBetween(Integer value1, Integer value2) {
            addCriterion("order_detail_id between", value1, value2, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_detail_id not between", value1, value2, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andCountsIsNull() {
            addCriterion("counts_ is null");
            return (Criteria) this;
        }

        public Criteria andCountsIsNotNull() {
            addCriterion("counts_ is not null");
            return (Criteria) this;
        }

        public Criteria andCountsEqualTo(Integer value) {
            addCriterion("counts_ =", value, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsNotEqualTo(Integer value) {
            addCriterion("counts_ <>", value, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsGreaterThan(Integer value) {
            addCriterion("counts_ >", value, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("counts_ >=", value, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsLessThan(Integer value) {
            addCriterion("counts_ <", value, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsLessThanOrEqualTo(Integer value) {
            addCriterion("counts_ <=", value, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsIn(List<Integer> values) {
            addCriterion("counts_ in", values, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsNotIn(List<Integer> values) {
            addCriterion("counts_ not in", values, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsBetween(Integer value1, Integer value2) {
            addCriterion("counts_ between", value1, value2, "counts");
            return (Criteria) this;
        }

        public Criteria andCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("counts_ not between", value1, value2, "counts");
            return (Criteria) this;
        }

        public Criteria andShopProductIdIsNull() {
            addCriterion("shop_product_id is null");
            return (Criteria) this;
        }

        public Criteria andShopProductIdIsNotNull() {
            addCriterion("shop_product_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopProductIdEqualTo(Integer value) {
            addCriterion("shop_product_id =", value, "shopProductId");
            return (Criteria) this;
        }

        public Criteria andShopProductIdNotEqualTo(Integer value) {
            addCriterion("shop_product_id <>", value, "shopProductId");
            return (Criteria) this;
        }

        public Criteria andShopProductIdGreaterThan(Integer value) {
            addCriterion("shop_product_id >", value, "shopProductId");
            return (Criteria) this;
        }

        public Criteria andShopProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_product_id >=", value, "shopProductId");
            return (Criteria) this;
        }

        public Criteria andShopProductIdLessThan(Integer value) {
            addCriterion("shop_product_id <", value, "shopProductId");
            return (Criteria) this;
        }

        public Criteria andShopProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_product_id <=", value, "shopProductId");
            return (Criteria) this;
        }

        public Criteria andShopProductIdIn(List<Integer> values) {
            addCriterion("shop_product_id in", values, "shopProductId");
            return (Criteria) this;
        }

        public Criteria andShopProductIdNotIn(List<Integer> values) {
            addCriterion("shop_product_id not in", values, "shopProductId");
            return (Criteria) this;
        }

        public Criteria andShopProductIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_product_id between", value1, value2, "shopProductId");
            return (Criteria) this;
        }

        public Criteria andShopProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_product_id not between", value1, value2, "shopProductId");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdIsNull() {
            addCriterion("third_product_id is null");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdIsNotNull() {
            addCriterion("third_product_id is not null");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdEqualTo(String value) {
            addCriterion("third_product_id =", value, "thirdProductId");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdNotEqualTo(String value) {
            addCriterion("third_product_id <>", value, "thirdProductId");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdGreaterThan(String value) {
            addCriterion("third_product_id >", value, "thirdProductId");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("third_product_id >=", value, "thirdProductId");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdLessThan(String value) {
            addCriterion("third_product_id <", value, "thirdProductId");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdLessThanOrEqualTo(String value) {
            addCriterion("third_product_id <=", value, "thirdProductId");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdLike(String value) {
            addCriterion("third_product_id like", value, "thirdProductId");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdNotLike(String value) {
            addCriterion("third_product_id not like", value, "thirdProductId");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdIn(List<String> values) {
            addCriterion("third_product_id in", values, "thirdProductId");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdNotIn(List<String> values) {
            addCriterion("third_product_id not in", values, "thirdProductId");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdBetween(String value1, String value2) {
            addCriterion("third_product_id between", value1, value2, "thirdProductId");
            return (Criteria) this;
        }

        public Criteria andThirdProductIdNotBetween(String value1, String value2) {
            addCriterion("third_product_id not between", value1, value2, "thirdProductId");
            return (Criteria) this;
        }

        public Criteria andCnPriceIsNull() {
            addCriterion("cn_price is null");
            return (Criteria) this;
        }

        public Criteria andCnPriceIsNotNull() {
            addCriterion("cn_price is not null");
            return (Criteria) this;
        }

        public Criteria andCnPriceEqualTo(Double value) {
            addCriterion("cn_price =", value, "cnPrice");
            return (Criteria) this;
        }

        public Criteria andCnPriceNotEqualTo(Double value) {
            addCriterion("cn_price <>", value, "cnPrice");
            return (Criteria) this;
        }

        public Criteria andCnPriceGreaterThan(Double value) {
            addCriterion("cn_price >", value, "cnPrice");
            return (Criteria) this;
        }

        public Criteria andCnPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("cn_price >=", value, "cnPrice");
            return (Criteria) this;
        }

        public Criteria andCnPriceLessThan(Double value) {
            addCriterion("cn_price <", value, "cnPrice");
            return (Criteria) this;
        }

        public Criteria andCnPriceLessThanOrEqualTo(Double value) {
            addCriterion("cn_price <=", value, "cnPrice");
            return (Criteria) this;
        }

        public Criteria andCnPriceIn(List<Double> values) {
            addCriterion("cn_price in", values, "cnPrice");
            return (Criteria) this;
        }

        public Criteria andCnPriceNotIn(List<Double> values) {
            addCriterion("cn_price not in", values, "cnPrice");
            return (Criteria) this;
        }

        public Criteria andCnPriceBetween(Double value1, Double value2) {
            addCriterion("cn_price between", value1, value2, "cnPrice");
            return (Criteria) this;
        }

        public Criteria andCnPriceNotBetween(Double value1, Double value2) {
            addCriterion("cn_price not between", value1, value2, "cnPrice");
            return (Criteria) this;
        }

        public Criteria andEnPriceIsNull() {
            addCriterion("en_price is null");
            return (Criteria) this;
        }

        public Criteria andEnPriceIsNotNull() {
            addCriterion("en_price is not null");
            return (Criteria) this;
        }

        public Criteria andEnPriceEqualTo(Double value) {
            addCriterion("en_price =", value, "enPrice");
            return (Criteria) this;
        }

        public Criteria andEnPriceNotEqualTo(Double value) {
            addCriterion("en_price <>", value, "enPrice");
            return (Criteria) this;
        }

        public Criteria andEnPriceGreaterThan(Double value) {
            addCriterion("en_price >", value, "enPrice");
            return (Criteria) this;
        }

        public Criteria andEnPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("en_price >=", value, "enPrice");
            return (Criteria) this;
        }

        public Criteria andEnPriceLessThan(Double value) {
            addCriterion("en_price <", value, "enPrice");
            return (Criteria) this;
        }

        public Criteria andEnPriceLessThanOrEqualTo(Double value) {
            addCriterion("en_price <=", value, "enPrice");
            return (Criteria) this;
        }

        public Criteria andEnPriceIn(List<Double> values) {
            addCriterion("en_price in", values, "enPrice");
            return (Criteria) this;
        }

        public Criteria andEnPriceNotIn(List<Double> values) {
            addCriterion("en_price not in", values, "enPrice");
            return (Criteria) this;
        }

        public Criteria andEnPriceBetween(Double value1, Double value2) {
            addCriterion("en_price between", value1, value2, "enPrice");
            return (Criteria) this;
        }

        public Criteria andEnPriceNotBetween(Double value1, Double value2) {
            addCriterion("en_price not between", value1, value2, "enPrice");
            return (Criteria) this;
        }

        public Criteria andShopProductNameIsNull() {
            addCriterion("shop_product_name is null");
            return (Criteria) this;
        }

        public Criteria andShopProductNameIsNotNull() {
            addCriterion("shop_product_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopProductNameEqualTo(String value) {
            addCriterion("shop_product_name =", value, "shopProductName");
            return (Criteria) this;
        }

        public Criteria andShopProductNameNotEqualTo(String value) {
            addCriterion("shop_product_name <>", value, "shopProductName");
            return (Criteria) this;
        }

        public Criteria andShopProductNameGreaterThan(String value) {
            addCriterion("shop_product_name >", value, "shopProductName");
            return (Criteria) this;
        }

        public Criteria andShopProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_product_name >=", value, "shopProductName");
            return (Criteria) this;
        }

        public Criteria andShopProductNameLessThan(String value) {
            addCriterion("shop_product_name <", value, "shopProductName");
            return (Criteria) this;
        }

        public Criteria andShopProductNameLessThanOrEqualTo(String value) {
            addCriterion("shop_product_name <=", value, "shopProductName");
            return (Criteria) this;
        }

        public Criteria andShopProductNameLike(String value) {
            addCriterion("shop_product_name like", value, "shopProductName");
            return (Criteria) this;
        }

        public Criteria andShopProductNameNotLike(String value) {
            addCriterion("shop_product_name not like", value, "shopProductName");
            return (Criteria) this;
        }

        public Criteria andShopProductNameIn(List<String> values) {
            addCriterion("shop_product_name in", values, "shopProductName");
            return (Criteria) this;
        }

        public Criteria andShopProductNameNotIn(List<String> values) {
            addCriterion("shop_product_name not in", values, "shopProductName");
            return (Criteria) this;
        }

        public Criteria andShopProductNameBetween(String value1, String value2) {
            addCriterion("shop_product_name between", value1, value2, "shopProductName");
            return (Criteria) this;
        }

        public Criteria andShopProductNameNotBetween(String value1, String value2) {
            addCriterion("shop_product_name not between", value1, value2, "shopProductName");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceIsNull() {
            addCriterion("shopbuyprice is null");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceIsNotNull() {
            addCriterion("shopbuyprice is not null");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceEqualTo(Double value) {
            addCriterion("shopbuyprice =", value, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceNotEqualTo(Double value) {
            addCriterion("shopbuyprice <>", value, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceGreaterThan(Double value) {
            addCriterion("shopbuyprice >", value, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceGreaterThanOrEqualTo(Double value) {
            addCriterion("shopbuyprice >=", value, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceLessThan(Double value) {
            addCriterion("shopbuyprice <", value, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceLessThanOrEqualTo(Double value) {
            addCriterion("shopbuyprice <=", value, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceIn(List<Double> values) {
            addCriterion("shopbuyprice in", values, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceNotIn(List<Double> values) {
            addCriterion("shopbuyprice not in", values, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceBetween(Double value1, Double value2) {
            addCriterion("shopbuyprice between", value1, value2, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceNotBetween(Double value1, Double value2) {
            addCriterion("shopbuyprice not between", value1, value2, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("stat is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("stat is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(Integer value) {
            addCriterion("stat =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(Integer value) {
            addCriterion("stat <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(Integer value) {
            addCriterion("stat >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("stat >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(Integer value) {
            addCriterion("stat <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(Integer value) {
            addCriterion("stat <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<Integer> values) {
            addCriterion("stat in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<Integer> values) {
            addCriterion("stat not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(Integer value1, Integer value2) {
            addCriterion("stat between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(Integer value1, Integer value2) {
            addCriterion("stat not between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andTicketDayIsNull() {
            addCriterion("ticket_day is null");
            return (Criteria) this;
        }

        public Criteria andTicketDayIsNotNull() {
            addCriterion("ticket_day is not null");
            return (Criteria) this;
        }

        public Criteria andTicketDayEqualTo(Date value) {
            addCriterion("ticket_day =", value, "ticketDay");
            return (Criteria) this;
        }

        public Criteria andTicketDayNotEqualTo(Date value) {
            addCriterion("ticket_day <>", value, "ticketDay");
            return (Criteria) this;
        }

        public Criteria andTicketDayGreaterThan(Date value) {
            addCriterion("ticket_day >", value, "ticketDay");
            return (Criteria) this;
        }

        public Criteria andTicketDayGreaterThanOrEqualTo(Date value) {
            addCriterion("ticket_day >=", value, "ticketDay");
            return (Criteria) this;
        }

        public Criteria andTicketDayLessThan(Date value) {
            addCriterion("ticket_day <", value, "ticketDay");
            return (Criteria) this;
        }

        public Criteria andTicketDayLessThanOrEqualTo(Date value) {
            addCriterion("ticket_day <=", value, "ticketDay");
            return (Criteria) this;
        }

        public Criteria andTicketDayIn(List<Date> values) {
            addCriterion("ticket_day in", values, "ticketDay");
            return (Criteria) this;
        }

        public Criteria andTicketDayNotIn(List<Date> values) {
            addCriterion("ticket_day not in", values, "ticketDay");
            return (Criteria) this;
        }

        public Criteria andTicketDayBetween(Date value1, Date value2) {
            addCriterion("ticket_day between", value1, value2, "ticketDay");
            return (Criteria) this;
        }

        public Criteria andTicketDayNotBetween(Date value1, Date value2) {
            addCriterion("ticket_day not between", value1, value2, "ticketDay");
            return (Criteria) this;
        }

        public Criteria andValidDaysIsNull() {
            addCriterion("valid_days is null");
            return (Criteria) this;
        }

        public Criteria andValidDaysIsNotNull() {
            addCriterion("valid_days is not null");
            return (Criteria) this;
        }

        public Criteria andValidDaysEqualTo(Integer value) {
            addCriterion("valid_days =", value, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysNotEqualTo(Integer value) {
            addCriterion("valid_days <>", value, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysGreaterThan(Integer value) {
            addCriterion("valid_days >", value, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("valid_days >=", value, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysLessThan(Integer value) {
            addCriterion("valid_days <", value, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysLessThanOrEqualTo(Integer value) {
            addCriterion("valid_days <=", value, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysIn(List<Integer> values) {
            addCriterion("valid_days in", values, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysNotIn(List<Integer> values) {
            addCriterion("valid_days not in", values, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysBetween(Integer value1, Integer value2) {
            addCriterion("valid_days between", value1, value2, "validDays");
            return (Criteria) this;
        }

        public Criteria andValidDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("valid_days not between", value1, value2, "validDays");
            return (Criteria) this;
        }

        public Criteria andPayPriceIsNull() {
            addCriterion("pay_price is null");
            return (Criteria) this;
        }

        public Criteria andPayPriceIsNotNull() {
            addCriterion("pay_price is not null");
            return (Criteria) this;
        }

        public Criteria andPayPriceEqualTo(Double value) {
            addCriterion("pay_price =", value, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceNotEqualTo(Double value) {
            addCriterion("pay_price <>", value, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceGreaterThan(Double value) {
            addCriterion("pay_price >", value, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("pay_price >=", value, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceLessThan(Double value) {
            addCriterion("pay_price <", value, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceLessThanOrEqualTo(Double value) {
            addCriterion("pay_price <=", value, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceIn(List<Double> values) {
            addCriterion("pay_price in", values, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceNotIn(List<Double> values) {
            addCriterion("pay_price not in", values, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceBetween(Double value1, Double value2) {
            addCriterion("pay_price between", value1, value2, "payPrice");
            return (Criteria) this;
        }

        public Criteria andPayPriceNotBetween(Double value1, Double value2) {
            addCriterion("pay_price not between", value1, value2, "payPrice");
            return (Criteria) this;
        }

        public Criteria andAccountPriceIsNull() {
            addCriterion("account_price is null");
            return (Criteria) this;
        }

        public Criteria andAccountPriceIsNotNull() {
            addCriterion("account_price is not null");
            return (Criteria) this;
        }

        public Criteria andAccountPriceEqualTo(Double value) {
            addCriterion("account_price =", value, "accountPrice");
            return (Criteria) this;
        }

        public Criteria andAccountPriceNotEqualTo(Double value) {
            addCriterion("account_price <>", value, "accountPrice");
            return (Criteria) this;
        }

        public Criteria andAccountPriceGreaterThan(Double value) {
            addCriterion("account_price >", value, "accountPrice");
            return (Criteria) this;
        }

        public Criteria andAccountPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("account_price >=", value, "accountPrice");
            return (Criteria) this;
        }

        public Criteria andAccountPriceLessThan(Double value) {
            addCriterion("account_price <", value, "accountPrice");
            return (Criteria) this;
        }

        public Criteria andAccountPriceLessThanOrEqualTo(Double value) {
            addCriterion("account_price <=", value, "accountPrice");
            return (Criteria) this;
        }

        public Criteria andAccountPriceIn(List<Double> values) {
            addCriterion("account_price in", values, "accountPrice");
            return (Criteria) this;
        }

        public Criteria andAccountPriceNotIn(List<Double> values) {
            addCriterion("account_price not in", values, "accountPrice");
            return (Criteria) this;
        }

        public Criteria andAccountPriceBetween(Double value1, Double value2) {
            addCriterion("account_price between", value1, value2, "accountPrice");
            return (Criteria) this;
        }

        public Criteria andAccountPriceNotBetween(Double value1, Double value2) {
            addCriterion("account_price not between", value1, value2, "accountPrice");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("shop_name is null");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("shop_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("shop_name =", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("shop_name <>", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("shop_name >", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_name >=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("shop_name <", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("shop_name <=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("shop_name like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("shop_name not like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameIn(List<String> values) {
            addCriterion("shop_name in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotIn(List<String> values) {
            addCriterion("shop_name not in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("shop_name between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("shop_name not between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Integer value) {
            addCriterion("shop_id =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Integer value) {
            addCriterion("shop_id <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Integer value) {
            addCriterion("shop_id >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_id >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Integer value) {
            addCriterion("shop_id <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_id <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Integer> values) {
            addCriterion("shop_id in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Integer> values) {
            addCriterion("shop_id not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andDayTicketTypeIsNull() {
            addCriterion("day_ticket_type is null");
            return (Criteria) this;
        }

        public Criteria andDayTicketTypeIsNotNull() {
            addCriterion("day_ticket_type is not null");
            return (Criteria) this;
        }

        public Criteria andDayTicketTypeEqualTo(Integer value) {
            addCriterion("day_ticket_type =", value, "dayTicketType");
            return (Criteria) this;
        }

        public Criteria andDayTicketTypeNotEqualTo(Integer value) {
            addCriterion("day_ticket_type <>", value, "dayTicketType");
            return (Criteria) this;
        }

        public Criteria andDayTicketTypeGreaterThan(Integer value) {
            addCriterion("day_ticket_type >", value, "dayTicketType");
            return (Criteria) this;
        }

        public Criteria andDayTicketTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("day_ticket_type >=", value, "dayTicketType");
            return (Criteria) this;
        }

        public Criteria andDayTicketTypeLessThan(Integer value) {
            addCriterion("day_ticket_type <", value, "dayTicketType");
            return (Criteria) this;
        }

        public Criteria andDayTicketTypeLessThanOrEqualTo(Integer value) {
            addCriterion("day_ticket_type <=", value, "dayTicketType");
            return (Criteria) this;
        }

        public Criteria andDayTicketTypeIn(List<Integer> values) {
            addCriterion("day_ticket_type in", values, "dayTicketType");
            return (Criteria) this;
        }

        public Criteria andDayTicketTypeNotIn(List<Integer> values) {
            addCriterion("day_ticket_type not in", values, "dayTicketType");
            return (Criteria) this;
        }

        public Criteria andDayTicketTypeBetween(Integer value1, Integer value2) {
            addCriterion("day_ticket_type between", value1, value2, "dayTicketType");
            return (Criteria) this;
        }

        public Criteria andDayTicketTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("day_ticket_type not between", value1, value2, "dayTicketType");
            return (Criteria) this;
        }

        public Criteria andPersonTicketTypeIsNull() {
            addCriterion("person_ticket_type is null");
            return (Criteria) this;
        }

        public Criteria andPersonTicketTypeIsNotNull() {
            addCriterion("person_ticket_type is not null");
            return (Criteria) this;
        }

        public Criteria andPersonTicketTypeEqualTo(Integer value) {
            addCriterion("person_ticket_type =", value, "personTicketType");
            return (Criteria) this;
        }

        public Criteria andPersonTicketTypeNotEqualTo(Integer value) {
            addCriterion("person_ticket_type <>", value, "personTicketType");
            return (Criteria) this;
        }

        public Criteria andPersonTicketTypeGreaterThan(Integer value) {
            addCriterion("person_ticket_type >", value, "personTicketType");
            return (Criteria) this;
        }

        public Criteria andPersonTicketTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("person_ticket_type >=", value, "personTicketType");
            return (Criteria) this;
        }

        public Criteria andPersonTicketTypeLessThan(Integer value) {
            addCriterion("person_ticket_type <", value, "personTicketType");
            return (Criteria) this;
        }

        public Criteria andPersonTicketTypeLessThanOrEqualTo(Integer value) {
            addCriterion("person_ticket_type <=", value, "personTicketType");
            return (Criteria) this;
        }

        public Criteria andPersonTicketTypeIn(List<Integer> values) {
            addCriterion("person_ticket_type in", values, "personTicketType");
            return (Criteria) this;
        }

        public Criteria andPersonTicketTypeNotIn(List<Integer> values) {
            addCriterion("person_ticket_type not in", values, "personTicketType");
            return (Criteria) this;
        }

        public Criteria andPersonTicketTypeBetween(Integer value1, Integer value2) {
            addCriterion("person_ticket_type between", value1, value2, "personTicketType");
            return (Criteria) this;
        }

        public Criteria andPersonTicketTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("person_ticket_type not between", value1, value2, "personTicketType");
            return (Criteria) this;
        }

        public Criteria andSeasonTicketTypeIsNull() {
            addCriterion("season_ticket_type is null");
            return (Criteria) this;
        }

        public Criteria andSeasonTicketTypeIsNotNull() {
            addCriterion("season_ticket_type is not null");
            return (Criteria) this;
        }

        public Criteria andSeasonTicketTypeEqualTo(Integer value) {
            addCriterion("season_ticket_type =", value, "seasonTicketType");
            return (Criteria) this;
        }

        public Criteria andSeasonTicketTypeNotEqualTo(Integer value) {
            addCriterion("season_ticket_type <>", value, "seasonTicketType");
            return (Criteria) this;
        }

        public Criteria andSeasonTicketTypeGreaterThan(Integer value) {
            addCriterion("season_ticket_type >", value, "seasonTicketType");
            return (Criteria) this;
        }

        public Criteria andSeasonTicketTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("season_ticket_type >=", value, "seasonTicketType");
            return (Criteria) this;
        }

        public Criteria andSeasonTicketTypeLessThan(Integer value) {
            addCriterion("season_ticket_type <", value, "seasonTicketType");
            return (Criteria) this;
        }

        public Criteria andSeasonTicketTypeLessThanOrEqualTo(Integer value) {
            addCriterion("season_ticket_type <=", value, "seasonTicketType");
            return (Criteria) this;
        }

        public Criteria andSeasonTicketTypeIn(List<Integer> values) {
            addCriterion("season_ticket_type in", values, "seasonTicketType");
            return (Criteria) this;
        }

        public Criteria andSeasonTicketTypeNotIn(List<Integer> values) {
            addCriterion("season_ticket_type not in", values, "seasonTicketType");
            return (Criteria) this;
        }

        public Criteria andSeasonTicketTypeBetween(Integer value1, Integer value2) {
            addCriterion("season_ticket_type between", value1, value2, "seasonTicketType");
            return (Criteria) this;
        }

        public Criteria andSeasonTicketTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("season_ticket_type not between", value1, value2, "seasonTicketType");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoIsNull() {
            addCriterion("third_order_no is null");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoIsNotNull() {
            addCriterion("third_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoEqualTo(String value) {
            addCriterion("third_order_no =", value, "thirdOrderNo");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoNotEqualTo(String value) {
            addCriterion("third_order_no <>", value, "thirdOrderNo");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoGreaterThan(String value) {
            addCriterion("third_order_no >", value, "thirdOrderNo");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("third_order_no >=", value, "thirdOrderNo");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoLessThan(String value) {
            addCriterion("third_order_no <", value, "thirdOrderNo");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoLessThanOrEqualTo(String value) {
            addCriterion("third_order_no <=", value, "thirdOrderNo");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoLike(String value) {
            addCriterion("third_order_no like", value, "thirdOrderNo");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoNotLike(String value) {
            addCriterion("third_order_no not like", value, "thirdOrderNo");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoIn(List<String> values) {
            addCriterion("third_order_no in", values, "thirdOrderNo");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoNotIn(List<String> values) {
            addCriterion("third_order_no not in", values, "thirdOrderNo");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoBetween(String value1, String value2) {
            addCriterion("third_order_no between", value1, value2, "thirdOrderNo");
            return (Criteria) this;
        }

        public Criteria andThirdOrderNoNotBetween(String value1, String value2) {
            addCriterion("third_order_no not between", value1, value2, "thirdOrderNo");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueIsNull() {
            addCriterion("barcode_value is null");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueIsNotNull() {
            addCriterion("barcode_value is not null");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueEqualTo(String value) {
            addCriterion("barcode_value =", value, "barcodeValue");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueNotEqualTo(String value) {
            addCriterion("barcode_value <>", value, "barcodeValue");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueGreaterThan(String value) {
            addCriterion("barcode_value >", value, "barcodeValue");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueGreaterThanOrEqualTo(String value) {
            addCriterion("barcode_value >=", value, "barcodeValue");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueLessThan(String value) {
            addCriterion("barcode_value <", value, "barcodeValue");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueLessThanOrEqualTo(String value) {
            addCriterion("barcode_value <=", value, "barcodeValue");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueLike(String value) {
            addCriterion("barcode_value like", value, "barcodeValue");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueNotLike(String value) {
            addCriterion("barcode_value not like", value, "barcodeValue");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueIn(List<String> values) {
            addCriterion("barcode_value in", values, "barcodeValue");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueNotIn(List<String> values) {
            addCriterion("barcode_value not in", values, "barcodeValue");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueBetween(String value1, String value2) {
            addCriterion("barcode_value between", value1, value2, "barcodeValue");
            return (Criteria) this;
        }

        public Criteria andBarcodeValueNotBetween(String value1, String value2) {
            addCriterion("barcode_value not between", value1, value2, "barcodeValue");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlIsNull() {
            addCriterion("barcode_url is null");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlIsNotNull() {
            addCriterion("barcode_url is not null");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlEqualTo(String value) {
            addCriterion("barcode_url =", value, "barcodeUrl");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlNotEqualTo(String value) {
            addCriterion("barcode_url <>", value, "barcodeUrl");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlGreaterThan(String value) {
            addCriterion("barcode_url >", value, "barcodeUrl");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlGreaterThanOrEqualTo(String value) {
            addCriterion("barcode_url >=", value, "barcodeUrl");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlLessThan(String value) {
            addCriterion("barcode_url <", value, "barcodeUrl");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlLessThanOrEqualTo(String value) {
            addCriterion("barcode_url <=", value, "barcodeUrl");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlLike(String value) {
            addCriterion("barcode_url like", value, "barcodeUrl");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlNotLike(String value) {
            addCriterion("barcode_url not like", value, "barcodeUrl");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlIn(List<String> values) {
            addCriterion("barcode_url in", values, "barcodeUrl");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlNotIn(List<String> values) {
            addCriterion("barcode_url not in", values, "barcodeUrl");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlBetween(String value1, String value2) {
            addCriterion("barcode_url between", value1, value2, "barcodeUrl");
            return (Criteria) this;
        }

        public Criteria andBarcodeUrlNotBetween(String value1, String value2) {
            addCriterion("barcode_url not between", value1, value2, "barcodeUrl");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeIsNull() {
            addCriterion("ticket_systype is null");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeIsNotNull() {
            addCriterion("ticket_systype is not null");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeEqualTo(Integer value) {
            addCriterion("ticket_systype =", value, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeNotEqualTo(Integer value) {
            addCriterion("ticket_systype <>", value, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeGreaterThan(Integer value) {
            addCriterion("ticket_systype >", value, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ticket_systype >=", value, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeLessThan(Integer value) {
            addCriterion("ticket_systype <", value, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeLessThanOrEqualTo(Integer value) {
            addCriterion("ticket_systype <=", value, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeIn(List<Integer> values) {
            addCriterion("ticket_systype in", values, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeNotIn(List<Integer> values) {
            addCriterion("ticket_systype not in", values, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeBetween(Integer value1, Integer value2) {
            addCriterion("ticket_systype between", value1, value2, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeNotBetween(Integer value1, Integer value2) {
            addCriterion("ticket_systype not between", value1, value2, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeIsNull() {
            addCriterion("gate_systype is null");
            return (Criteria) this;
        }

        public Criteria andGateSystypeIsNotNull() {
            addCriterion("gate_systype is not null");
            return (Criteria) this;
        }

        public Criteria andGateSystypeEqualTo(Integer value) {
            addCriterion("gate_systype =", value, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeNotEqualTo(Integer value) {
            addCriterion("gate_systype <>", value, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeGreaterThan(Integer value) {
            addCriterion("gate_systype >", value, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("gate_systype >=", value, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeLessThan(Integer value) {
            addCriterion("gate_systype <", value, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeLessThanOrEqualTo(Integer value) {
            addCriterion("gate_systype <=", value, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeIn(List<Integer> values) {
            addCriterion("gate_systype in", values, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeNotIn(List<Integer> values) {
            addCriterion("gate_systype not in", values, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeBetween(Integer value1, Integer value2) {
            addCriterion("gate_systype between", value1, value2, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeNotBetween(Integer value1, Integer value2) {
            addCriterion("gate_systype not between", value1, value2, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 21 12:39:41 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}