package com.cuize.task.dao.order.domain;

import java.util.Date;

public class OrderDetailPackdtl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.order_detail_id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer orderDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.counts_
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer counts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.shop_product_id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer shopProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.third_product_id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private String thirdProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.cn_price
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Double cnPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.en_price
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Double enPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.shop_product_name
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private String shopProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.shopbuyprice
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Double shopbuyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.stat
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.ticket_day
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Date ticketDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.valid_days
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer validDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.pay_price
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Double payPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.account_price
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Double accountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.shop_name
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.shop_id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.day_ticket_type
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer dayTicketType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.person_ticket_type
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer personTicketType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.season_ticket_type
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer seasonTicketType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.remark
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.third_order_no
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private String thirdOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.barcode_value
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private String barcodeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.barcode_url
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private String barcodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.ticket_systype
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer ticketSystype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.gate_systype
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer gateSystype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.create_time
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.update_time
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_packdtl.version
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.id
     *
     * @return the value of order_detail_packdtl.id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.id
     *
     * @param id the value for order_detail_packdtl.id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.order_detail_id
     *
     * @return the value of order_detail_packdtl.order_detail_id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.order_detail_id
     *
     * @param orderDetailId the value for order_detail_packdtl.order_detail_id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.counts_
     *
     * @return the value of order_detail_packdtl.counts_
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.counts_
     *
     * @param counts the value for order_detail_packdtl.counts_
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.shop_product_id
     *
     * @return the value of order_detail_packdtl.shop_product_id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getShopProductId() {
        return shopProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.shop_product_id
     *
     * @param shopProductId the value for order_detail_packdtl.shop_product_id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setShopProductId(Integer shopProductId) {
        this.shopProductId = shopProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.third_product_id
     *
     * @return the value of order_detail_packdtl.third_product_id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public String getThirdProductId() {
        return thirdProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.third_product_id
     *
     * @param thirdProductId the value for order_detail_packdtl.third_product_id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setThirdProductId(String thirdProductId) {
        this.thirdProductId = thirdProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.cn_price
     *
     * @return the value of order_detail_packdtl.cn_price
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Double getCnPrice() {
        return cnPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.cn_price
     *
     * @param cnPrice the value for order_detail_packdtl.cn_price
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setCnPrice(Double cnPrice) {
        this.cnPrice = cnPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.en_price
     *
     * @return the value of order_detail_packdtl.en_price
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Double getEnPrice() {
        return enPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.en_price
     *
     * @param enPrice the value for order_detail_packdtl.en_price
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setEnPrice(Double enPrice) {
        this.enPrice = enPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.shop_product_name
     *
     * @return the value of order_detail_packdtl.shop_product_name
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public String getShopProductName() {
        return shopProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.shop_product_name
     *
     * @param shopProductName the value for order_detail_packdtl.shop_product_name
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setShopProductName(String shopProductName) {
        this.shopProductName = shopProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.shopbuyprice
     *
     * @return the value of order_detail_packdtl.shopbuyprice
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Double getShopbuyprice() {
        return shopbuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.shopbuyprice
     *
     * @param shopbuyprice the value for order_detail_packdtl.shopbuyprice
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setShopbuyprice(Double shopbuyprice) {
        this.shopbuyprice = shopbuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.stat
     *
     * @return the value of order_detail_packdtl.stat
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.stat
     *
     * @param stat the value for order_detail_packdtl.stat
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.ticket_day
     *
     * @return the value of order_detail_packdtl.ticket_day
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Date getTicketDay() {
        return ticketDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.ticket_day
     *
     * @param ticketDay the value for order_detail_packdtl.ticket_day
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setTicketDay(Date ticketDay) {
        this.ticketDay = ticketDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.valid_days
     *
     * @return the value of order_detail_packdtl.valid_days
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getValidDays() {
        return validDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.valid_days
     *
     * @param validDays the value for order_detail_packdtl.valid_days
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setValidDays(Integer validDays) {
        this.validDays = validDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.pay_price
     *
     * @return the value of order_detail_packdtl.pay_price
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Double getPayPrice() {
        return payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.pay_price
     *
     * @param payPrice the value for order_detail_packdtl.pay_price
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setPayPrice(Double payPrice) {
        this.payPrice = payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.account_price
     *
     * @return the value of order_detail_packdtl.account_price
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Double getAccountPrice() {
        return accountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.account_price
     *
     * @param accountPrice the value for order_detail_packdtl.account_price
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setAccountPrice(Double accountPrice) {
        this.accountPrice = accountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.shop_name
     *
     * @return the value of order_detail_packdtl.shop_name
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.shop_name
     *
     * @param shopName the value for order_detail_packdtl.shop_name
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.shop_id
     *
     * @return the value of order_detail_packdtl.shop_id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.shop_id
     *
     * @param shopId the value for order_detail_packdtl.shop_id
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.day_ticket_type
     *
     * @return the value of order_detail_packdtl.day_ticket_type
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getDayTicketType() {
        return dayTicketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.day_ticket_type
     *
     * @param dayTicketType the value for order_detail_packdtl.day_ticket_type
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setDayTicketType(Integer dayTicketType) {
        this.dayTicketType = dayTicketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.person_ticket_type
     *
     * @return the value of order_detail_packdtl.person_ticket_type
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getPersonTicketType() {
        return personTicketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.person_ticket_type
     *
     * @param personTicketType the value for order_detail_packdtl.person_ticket_type
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setPersonTicketType(Integer personTicketType) {
        this.personTicketType = personTicketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.season_ticket_type
     *
     * @return the value of order_detail_packdtl.season_ticket_type
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getSeasonTicketType() {
        return seasonTicketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.season_ticket_type
     *
     * @param seasonTicketType the value for order_detail_packdtl.season_ticket_type
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setSeasonTicketType(Integer seasonTicketType) {
        this.seasonTicketType = seasonTicketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.remark
     *
     * @return the value of order_detail_packdtl.remark
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.remark
     *
     * @param remark the value for order_detail_packdtl.remark
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.third_order_no
     *
     * @return the value of order_detail_packdtl.third_order_no
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public String getThirdOrderNo() {
        return thirdOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.third_order_no
     *
     * @param thirdOrderNo the value for order_detail_packdtl.third_order_no
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setThirdOrderNo(String thirdOrderNo) {
        this.thirdOrderNo = thirdOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.barcode_value
     *
     * @return the value of order_detail_packdtl.barcode_value
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public String getBarcodeValue() {
        return barcodeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.barcode_value
     *
     * @param barcodeValue the value for order_detail_packdtl.barcode_value
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setBarcodeValue(String barcodeValue) {
        this.barcodeValue = barcodeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.barcode_url
     *
     * @return the value of order_detail_packdtl.barcode_url
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public String getBarcodeUrl() {
        return barcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.barcode_url
     *
     * @param barcodeUrl the value for order_detail_packdtl.barcode_url
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setBarcodeUrl(String barcodeUrl) {
        this.barcodeUrl = barcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.ticket_systype
     *
     * @return the value of order_detail_packdtl.ticket_systype
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getTicketSystype() {
        return ticketSystype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.ticket_systype
     *
     * @param ticketSystype the value for order_detail_packdtl.ticket_systype
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setTicketSystype(Integer ticketSystype) {
        this.ticketSystype = ticketSystype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.gate_systype
     *
     * @return the value of order_detail_packdtl.gate_systype
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getGateSystype() {
        return gateSystype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.gate_systype
     *
     * @param gateSystype the value for order_detail_packdtl.gate_systype
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setGateSystype(Integer gateSystype) {
        this.gateSystype = gateSystype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.create_time
     *
     * @return the value of order_detail_packdtl.create_time
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.create_time
     *
     * @param createTime the value for order_detail_packdtl.create_time
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.update_time
     *
     * @return the value of order_detail_packdtl.update_time
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.update_time
     *
     * @param updateTime the value for order_detail_packdtl.update_time
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_packdtl.version
     *
     * @return the value of order_detail_packdtl.version
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_packdtl.version
     *
     * @param version the value for order_detail_packdtl.version
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}