package com.cuize.task.dao.order.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("order_no =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("order_no <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("order_no >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("order_no >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("order_no <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("order_no <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("order_no like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("order_no not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("order_no in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("order_no not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("order_no between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("order_no not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCommitTimeIsNull() {
            addCriterion("commit_time is null");
            return (Criteria) this;
        }

        public Criteria andCommitTimeIsNotNull() {
            addCriterion("commit_time is not null");
            return (Criteria) this;
        }

        public Criteria andCommitTimeEqualTo(Date value) {
            addCriterion("commit_time =", value, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeNotEqualTo(Date value) {
            addCriterion("commit_time <>", value, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeGreaterThan(Date value) {
            addCriterion("commit_time >", value, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("commit_time >=", value, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeLessThan(Date value) {
            addCriterion("commit_time <", value, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeLessThanOrEqualTo(Date value) {
            addCriterion("commit_time <=", value, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeIn(List<Date> values) {
            addCriterion("commit_time in", values, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeNotIn(List<Date> values) {
            addCriterion("commit_time not in", values, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeBetween(Date value1, Date value2) {
            addCriterion("commit_time between", value1, value2, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeNotBetween(Date value1, Date value2) {
            addCriterion("commit_time not between", value1, value2, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCnDistributionFeeIsNull() {
            addCriterion("cn_distribution_fee is null");
            return (Criteria) this;
        }

        public Criteria andCnDistributionFeeIsNotNull() {
            addCriterion("cn_distribution_fee is not null");
            return (Criteria) this;
        }

        public Criteria andCnDistributionFeeEqualTo(Double value) {
            addCriterion("cn_distribution_fee =", value, "cnDistributionFee");
            return (Criteria) this;
        }

        public Criteria andCnDistributionFeeNotEqualTo(Double value) {
            addCriterion("cn_distribution_fee <>", value, "cnDistributionFee");
            return (Criteria) this;
        }

        public Criteria andCnDistributionFeeGreaterThan(Double value) {
            addCriterion("cn_distribution_fee >", value, "cnDistributionFee");
            return (Criteria) this;
        }

        public Criteria andCnDistributionFeeGreaterThanOrEqualTo(Double value) {
            addCriterion("cn_distribution_fee >=", value, "cnDistributionFee");
            return (Criteria) this;
        }

        public Criteria andCnDistributionFeeLessThan(Double value) {
            addCriterion("cn_distribution_fee <", value, "cnDistributionFee");
            return (Criteria) this;
        }

        public Criteria andCnDistributionFeeLessThanOrEqualTo(Double value) {
            addCriterion("cn_distribution_fee <=", value, "cnDistributionFee");
            return (Criteria) this;
        }

        public Criteria andCnDistributionFeeIn(List<Double> values) {
            addCriterion("cn_distribution_fee in", values, "cnDistributionFee");
            return (Criteria) this;
        }

        public Criteria andCnDistributionFeeNotIn(List<Double> values) {
            addCriterion("cn_distribution_fee not in", values, "cnDistributionFee");
            return (Criteria) this;
        }

        public Criteria andCnDistributionFeeBetween(Double value1, Double value2) {
            addCriterion("cn_distribution_fee between", value1, value2, "cnDistributionFee");
            return (Criteria) this;
        }

        public Criteria andCnDistributionFeeNotBetween(Double value1, Double value2) {
            addCriterion("cn_distribution_fee not between", value1, value2, "cnDistributionFee");
            return (Criteria) this;
        }

        public Criteria andEnDistributionFeeIsNull() {
            addCriterion("en_distribution_fee is null");
            return (Criteria) this;
        }

        public Criteria andEnDistributionFeeIsNotNull() {
            addCriterion("en_distribution_fee is not null");
            return (Criteria) this;
        }

        public Criteria andEnDistributionFeeEqualTo(Double value) {
            addCriterion("en_distribution_fee =", value, "enDistributionFee");
            return (Criteria) this;
        }

        public Criteria andEnDistributionFeeNotEqualTo(Double value) {
            addCriterion("en_distribution_fee <>", value, "enDistributionFee");
            return (Criteria) this;
        }

        public Criteria andEnDistributionFeeGreaterThan(Double value) {
            addCriterion("en_distribution_fee >", value, "enDistributionFee");
            return (Criteria) this;
        }

        public Criteria andEnDistributionFeeGreaterThanOrEqualTo(Double value) {
            addCriterion("en_distribution_fee >=", value, "enDistributionFee");
            return (Criteria) this;
        }

        public Criteria andEnDistributionFeeLessThan(Double value) {
            addCriterion("en_distribution_fee <", value, "enDistributionFee");
            return (Criteria) this;
        }

        public Criteria andEnDistributionFeeLessThanOrEqualTo(Double value) {
            addCriterion("en_distribution_fee <=", value, "enDistributionFee");
            return (Criteria) this;
        }

        public Criteria andEnDistributionFeeIn(List<Double> values) {
            addCriterion("en_distribution_fee in", values, "enDistributionFee");
            return (Criteria) this;
        }

        public Criteria andEnDistributionFeeNotIn(List<Double> values) {
            addCriterion("en_distribution_fee not in", values, "enDistributionFee");
            return (Criteria) this;
        }

        public Criteria andEnDistributionFeeBetween(Double value1, Double value2) {
            addCriterion("en_distribution_fee between", value1, value2, "enDistributionFee");
            return (Criteria) this;
        }

        public Criteria andEnDistributionFeeNotBetween(Double value1, Double value2) {
            addCriterion("en_distribution_fee not between", value1, value2, "enDistributionFee");
            return (Criteria) this;
        }

        public Criteria andDistributionAddressIdIsNull() {
            addCriterion("distribution_address_id is null");
            return (Criteria) this;
        }

        public Criteria andDistributionAddressIdIsNotNull() {
            addCriterion("distribution_address_id is not null");
            return (Criteria) this;
        }

        public Criteria andDistributionAddressIdEqualTo(Integer value) {
            addCriterion("distribution_address_id =", value, "distributionAddressId");
            return (Criteria) this;
        }

        public Criteria andDistributionAddressIdNotEqualTo(Integer value) {
            addCriterion("distribution_address_id <>", value, "distributionAddressId");
            return (Criteria) this;
        }

        public Criteria andDistributionAddressIdGreaterThan(Integer value) {
            addCriterion("distribution_address_id >", value, "distributionAddressId");
            return (Criteria) this;
        }

        public Criteria andDistributionAddressIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("distribution_address_id >=", value, "distributionAddressId");
            return (Criteria) this;
        }

        public Criteria andDistributionAddressIdLessThan(Integer value) {
            addCriterion("distribution_address_id <", value, "distributionAddressId");
            return (Criteria) this;
        }

        public Criteria andDistributionAddressIdLessThanOrEqualTo(Integer value) {
            addCriterion("distribution_address_id <=", value, "distributionAddressId");
            return (Criteria) this;
        }

        public Criteria andDistributionAddressIdIn(List<Integer> values) {
            addCriterion("distribution_address_id in", values, "distributionAddressId");
            return (Criteria) this;
        }

        public Criteria andDistributionAddressIdNotIn(List<Integer> values) {
            addCriterion("distribution_address_id not in", values, "distributionAddressId");
            return (Criteria) this;
        }

        public Criteria andDistributionAddressIdBetween(Integer value1, Integer value2) {
            addCriterion("distribution_address_id between", value1, value2, "distributionAddressId");
            return (Criteria) this;
        }

        public Criteria andDistributionAddressIdNotBetween(Integer value1, Integer value2) {
            addCriterion("distribution_address_id not between", value1, value2, "distributionAddressId");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Integer value) {
            addCriterion("shop_id =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Integer value) {
            addCriterion("shop_id <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Integer value) {
            addCriterion("shop_id >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_id >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Integer value) {
            addCriterion("shop_id <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_id <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Integer> values) {
            addCriterion("shop_id in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Integer> values) {
            addCriterion("shop_id not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationIsNull() {
            addCriterion("en_user_evaluation is null");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationIsNotNull() {
            addCriterion("en_user_evaluation is not null");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationEqualTo(String value) {
            addCriterion("en_user_evaluation =", value, "enUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationNotEqualTo(String value) {
            addCriterion("en_user_evaluation <>", value, "enUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationGreaterThan(String value) {
            addCriterion("en_user_evaluation >", value, "enUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationGreaterThanOrEqualTo(String value) {
            addCriterion("en_user_evaluation >=", value, "enUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationLessThan(String value) {
            addCriterion("en_user_evaluation <", value, "enUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationLessThanOrEqualTo(String value) {
            addCriterion("en_user_evaluation <=", value, "enUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationLike(String value) {
            addCriterion("en_user_evaluation like", value, "enUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationNotLike(String value) {
            addCriterion("en_user_evaluation not like", value, "enUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationIn(List<String> values) {
            addCriterion("en_user_evaluation in", values, "enUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationNotIn(List<String> values) {
            addCriterion("en_user_evaluation not in", values, "enUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationBetween(String value1, String value2) {
            addCriterion("en_user_evaluation between", value1, value2, "enUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andEnUserEvaluationNotBetween(String value1, String value2) {
            addCriterion("en_user_evaluation not between", value1, value2, "enUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationIsNull() {
            addCriterion("cn_user_evaluation is null");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationIsNotNull() {
            addCriterion("cn_user_evaluation is not null");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationEqualTo(String value) {
            addCriterion("cn_user_evaluation =", value, "cnUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationNotEqualTo(String value) {
            addCriterion("cn_user_evaluation <>", value, "cnUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationGreaterThan(String value) {
            addCriterion("cn_user_evaluation >", value, "cnUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationGreaterThanOrEqualTo(String value) {
            addCriterion("cn_user_evaluation >=", value, "cnUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationLessThan(String value) {
            addCriterion("cn_user_evaluation <", value, "cnUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationLessThanOrEqualTo(String value) {
            addCriterion("cn_user_evaluation <=", value, "cnUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationLike(String value) {
            addCriterion("cn_user_evaluation like", value, "cnUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationNotLike(String value) {
            addCriterion("cn_user_evaluation not like", value, "cnUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationIn(List<String> values) {
            addCriterion("cn_user_evaluation in", values, "cnUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationNotIn(List<String> values) {
            addCriterion("cn_user_evaluation not in", values, "cnUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationBetween(String value1, String value2) {
            addCriterion("cn_user_evaluation between", value1, value2, "cnUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCnUserEvaluationNotBetween(String value1, String value2) {
            addCriterion("cn_user_evaluation not between", value1, value2, "cnUserEvaluation");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("shop_name is null");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("shop_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("shop_name =", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("shop_name <>", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("shop_name >", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_name >=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("shop_name <", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("shop_name <=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("shop_name like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("shop_name not like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameIn(List<String> values) {
            addCriterion("shop_name in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotIn(List<String> values) {
            addCriterion("shop_name not in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("shop_name between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("shop_name not between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andEnRemarkIsNull() {
            addCriterion("en_remark is null");
            return (Criteria) this;
        }

        public Criteria andEnRemarkIsNotNull() {
            addCriterion("en_remark is not null");
            return (Criteria) this;
        }

        public Criteria andEnRemarkEqualTo(String value) {
            addCriterion("en_remark =", value, "enRemark");
            return (Criteria) this;
        }

        public Criteria andEnRemarkNotEqualTo(String value) {
            addCriterion("en_remark <>", value, "enRemark");
            return (Criteria) this;
        }

        public Criteria andEnRemarkGreaterThan(String value) {
            addCriterion("en_remark >", value, "enRemark");
            return (Criteria) this;
        }

        public Criteria andEnRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("en_remark >=", value, "enRemark");
            return (Criteria) this;
        }

        public Criteria andEnRemarkLessThan(String value) {
            addCriterion("en_remark <", value, "enRemark");
            return (Criteria) this;
        }

        public Criteria andEnRemarkLessThanOrEqualTo(String value) {
            addCriterion("en_remark <=", value, "enRemark");
            return (Criteria) this;
        }

        public Criteria andEnRemarkLike(String value) {
            addCriterion("en_remark like", value, "enRemark");
            return (Criteria) this;
        }

        public Criteria andEnRemarkNotLike(String value) {
            addCriterion("en_remark not like", value, "enRemark");
            return (Criteria) this;
        }

        public Criteria andEnRemarkIn(List<String> values) {
            addCriterion("en_remark in", values, "enRemark");
            return (Criteria) this;
        }

        public Criteria andEnRemarkNotIn(List<String> values) {
            addCriterion("en_remark not in", values, "enRemark");
            return (Criteria) this;
        }

        public Criteria andEnRemarkBetween(String value1, String value2) {
            addCriterion("en_remark between", value1, value2, "enRemark");
            return (Criteria) this;
        }

        public Criteria andEnRemarkNotBetween(String value1, String value2) {
            addCriterion("en_remark not between", value1, value2, "enRemark");
            return (Criteria) this;
        }

        public Criteria andCnRemarkIsNull() {
            addCriterion("cn_remark is null");
            return (Criteria) this;
        }

        public Criteria andCnRemarkIsNotNull() {
            addCriterion("cn_remark is not null");
            return (Criteria) this;
        }

        public Criteria andCnRemarkEqualTo(String value) {
            addCriterion("cn_remark =", value, "cnRemark");
            return (Criteria) this;
        }

        public Criteria andCnRemarkNotEqualTo(String value) {
            addCriterion("cn_remark <>", value, "cnRemark");
            return (Criteria) this;
        }

        public Criteria andCnRemarkGreaterThan(String value) {
            addCriterion("cn_remark >", value, "cnRemark");
            return (Criteria) this;
        }

        public Criteria andCnRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("cn_remark >=", value, "cnRemark");
            return (Criteria) this;
        }

        public Criteria andCnRemarkLessThan(String value) {
            addCriterion("cn_remark <", value, "cnRemark");
            return (Criteria) this;
        }

        public Criteria andCnRemarkLessThanOrEqualTo(String value) {
            addCriterion("cn_remark <=", value, "cnRemark");
            return (Criteria) this;
        }

        public Criteria andCnRemarkLike(String value) {
            addCriterion("cn_remark like", value, "cnRemark");
            return (Criteria) this;
        }

        public Criteria andCnRemarkNotLike(String value) {
            addCriterion("cn_remark not like", value, "cnRemark");
            return (Criteria) this;
        }

        public Criteria andCnRemarkIn(List<String> values) {
            addCriterion("cn_remark in", values, "cnRemark");
            return (Criteria) this;
        }

        public Criteria andCnRemarkNotIn(List<String> values) {
            addCriterion("cn_remark not in", values, "cnRemark");
            return (Criteria) this;
        }

        public Criteria andCnRemarkBetween(String value1, String value2) {
            addCriterion("cn_remark between", value1, value2, "cnRemark");
            return (Criteria) this;
        }

        public Criteria andCnRemarkNotBetween(String value1, String value2) {
            addCriterion("cn_remark not between", value1, value2, "cnRemark");
            return (Criteria) this;
        }

        public Criteria andOrderTimeIsNull() {
            addCriterion("order_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderTimeIsNotNull() {
            addCriterion("order_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTimeEqualTo(String value) {
            addCriterion("order_time =", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotEqualTo(String value) {
            addCriterion("order_time <>", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeGreaterThan(String value) {
            addCriterion("order_time >", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeGreaterThanOrEqualTo(String value) {
            addCriterion("order_time >=", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeLessThan(String value) {
            addCriterion("order_time <", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeLessThanOrEqualTo(String value) {
            addCriterion("order_time <=", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeLike(String value) {
            addCriterion("order_time like", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotLike(String value) {
            addCriterion("order_time not like", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeIn(List<String> values) {
            addCriterion("order_time in", values, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotIn(List<String> values) {
            addCriterion("order_time not in", values, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeBetween(String value1, String value2) {
            addCriterion("order_time between", value1, value2, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotBetween(String value1, String value2) {
            addCriterion("order_time not between", value1, value2, "orderTime");
            return (Criteria) this;
        }

        public Criteria andShopkeeperidIsNull() {
            addCriterion("shopkeeperid is null");
            return (Criteria) this;
        }

        public Criteria andShopkeeperidIsNotNull() {
            addCriterion("shopkeeperid is not null");
            return (Criteria) this;
        }

        public Criteria andShopkeeperidEqualTo(Integer value) {
            addCriterion("shopkeeperid =", value, "shopkeeperid");
            return (Criteria) this;
        }

        public Criteria andShopkeeperidNotEqualTo(Integer value) {
            addCriterion("shopkeeperid <>", value, "shopkeeperid");
            return (Criteria) this;
        }

        public Criteria andShopkeeperidGreaterThan(Integer value) {
            addCriterion("shopkeeperid >", value, "shopkeeperid");
            return (Criteria) this;
        }

        public Criteria andShopkeeperidGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopkeeperid >=", value, "shopkeeperid");
            return (Criteria) this;
        }

        public Criteria andShopkeeperidLessThan(Integer value) {
            addCriterion("shopkeeperid <", value, "shopkeeperid");
            return (Criteria) this;
        }

        public Criteria andShopkeeperidLessThanOrEqualTo(Integer value) {
            addCriterion("shopkeeperid <=", value, "shopkeeperid");
            return (Criteria) this;
        }

        public Criteria andShopkeeperidIn(List<Integer> values) {
            addCriterion("shopkeeperid in", values, "shopkeeperid");
            return (Criteria) this;
        }

        public Criteria andShopkeeperidNotIn(List<Integer> values) {
            addCriterion("shopkeeperid not in", values, "shopkeeperid");
            return (Criteria) this;
        }

        public Criteria andShopkeeperidBetween(Integer value1, Integer value2) {
            addCriterion("shopkeeperid between", value1, value2, "shopkeeperid");
            return (Criteria) this;
        }

        public Criteria andShopkeeperidNotBetween(Integer value1, Integer value2) {
            addCriterion("shopkeeperid not between", value1, value2, "shopkeeperid");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameIsNull() {
            addCriterion("shopkeeper_username is null");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameIsNotNull() {
            addCriterion("shopkeeper_username is not null");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameEqualTo(String value) {
            addCriterion("shopkeeper_username =", value, "shopkeeperUsername");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameNotEqualTo(String value) {
            addCriterion("shopkeeper_username <>", value, "shopkeeperUsername");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameGreaterThan(String value) {
            addCriterion("shopkeeper_username >", value, "shopkeeperUsername");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("shopkeeper_username >=", value, "shopkeeperUsername");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameLessThan(String value) {
            addCriterion("shopkeeper_username <", value, "shopkeeperUsername");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameLessThanOrEqualTo(String value) {
            addCriterion("shopkeeper_username <=", value, "shopkeeperUsername");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameLike(String value) {
            addCriterion("shopkeeper_username like", value, "shopkeeperUsername");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameNotLike(String value) {
            addCriterion("shopkeeper_username not like", value, "shopkeeperUsername");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameIn(List<String> values) {
            addCriterion("shopkeeper_username in", values, "shopkeeperUsername");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameNotIn(List<String> values) {
            addCriterion("shopkeeper_username not in", values, "shopkeeperUsername");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameBetween(String value1, String value2) {
            addCriterion("shopkeeper_username between", value1, value2, "shopkeeperUsername");
            return (Criteria) this;
        }

        public Criteria andShopkeeperUsernameNotBetween(String value1, String value2) {
            addCriterion("shopkeeper_username not between", value1, value2, "shopkeeperUsername");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdIsNull() {
            addCriterion("delivery_id is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdIsNotNull() {
            addCriterion("delivery_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdEqualTo(Integer value) {
            addCriterion("delivery_id =", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdNotEqualTo(Integer value) {
            addCriterion("delivery_id <>", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdGreaterThan(Integer value) {
            addCriterion("delivery_id >", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("delivery_id >=", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdLessThan(Integer value) {
            addCriterion("delivery_id <", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdLessThanOrEqualTo(Integer value) {
            addCriterion("delivery_id <=", value, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdIn(List<Integer> values) {
            addCriterion("delivery_id in", values, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdNotIn(List<Integer> values) {
            addCriterion("delivery_id not in", values, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdBetween(Integer value1, Integer value2) {
            addCriterion("delivery_id between", value1, value2, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andDeliveryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("delivery_id not between", value1, value2, "deliveryId");
            return (Criteria) this;
        }

        public Criteria andOrderAffirmantIsNull() {
            addCriterion("order_affirmant is null");
            return (Criteria) this;
        }

        public Criteria andOrderAffirmantIsNotNull() {
            addCriterion("order_affirmant is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAffirmantEqualTo(Integer value) {
            addCriterion("order_affirmant =", value, "orderAffirmant");
            return (Criteria) this;
        }

        public Criteria andOrderAffirmantNotEqualTo(Integer value) {
            addCriterion("order_affirmant <>", value, "orderAffirmant");
            return (Criteria) this;
        }

        public Criteria andOrderAffirmantGreaterThan(Integer value) {
            addCriterion("order_affirmant >", value, "orderAffirmant");
            return (Criteria) this;
        }

        public Criteria andOrderAffirmantGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_affirmant >=", value, "orderAffirmant");
            return (Criteria) this;
        }

        public Criteria andOrderAffirmantLessThan(Integer value) {
            addCriterion("order_affirmant <", value, "orderAffirmant");
            return (Criteria) this;
        }

        public Criteria andOrderAffirmantLessThanOrEqualTo(Integer value) {
            addCriterion("order_affirmant <=", value, "orderAffirmant");
            return (Criteria) this;
        }

        public Criteria andOrderAffirmantIn(List<Integer> values) {
            addCriterion("order_affirmant in", values, "orderAffirmant");
            return (Criteria) this;
        }

        public Criteria andOrderAffirmantNotIn(List<Integer> values) {
            addCriterion("order_affirmant not in", values, "orderAffirmant");
            return (Criteria) this;
        }

        public Criteria andOrderAffirmantBetween(Integer value1, Integer value2) {
            addCriterion("order_affirmant between", value1, value2, "orderAffirmant");
            return (Criteria) this;
        }

        public Criteria andOrderAffirmantNotBetween(Integer value1, Integer value2) {
            addCriterion("order_affirmant not between", value1, value2, "orderAffirmant");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceIsNull() {
            addCriterion("shopbuyprice is null");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceIsNotNull() {
            addCriterion("shopbuyprice is not null");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceEqualTo(Double value) {
            addCriterion("shopbuyprice =", value, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceNotEqualTo(Double value) {
            addCriterion("shopbuyprice <>", value, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceGreaterThan(Double value) {
            addCriterion("shopbuyprice >", value, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceGreaterThanOrEqualTo(Double value) {
            addCriterion("shopbuyprice >=", value, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceLessThan(Double value) {
            addCriterion("shopbuyprice <", value, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceLessThanOrEqualTo(Double value) {
            addCriterion("shopbuyprice <=", value, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceIn(List<Double> values) {
            addCriterion("shopbuyprice in", values, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceNotIn(List<Double> values) {
            addCriterion("shopbuyprice not in", values, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceBetween(Double value1, Double value2) {
            addCriterion("shopbuyprice between", value1, value2, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andShopbuypriceNotBetween(Double value1, Double value2) {
            addCriterion("shopbuyprice not between", value1, value2, "shopbuyprice");
            return (Criteria) this;
        }

        public Criteria andMobilephoneIsNull() {
            addCriterion("mobilephone is null");
            return (Criteria) this;
        }

        public Criteria andMobilephoneIsNotNull() {
            addCriterion("mobilephone is not null");
            return (Criteria) this;
        }

        public Criteria andMobilephoneEqualTo(String value) {
            addCriterion("mobilephone =", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneNotEqualTo(String value) {
            addCriterion("mobilephone <>", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneGreaterThan(String value) {
            addCriterion("mobilephone >", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneGreaterThanOrEqualTo(String value) {
            addCriterion("mobilephone >=", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneLessThan(String value) {
            addCriterion("mobilephone <", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneLessThanOrEqualTo(String value) {
            addCriterion("mobilephone <=", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneLike(String value) {
            addCriterion("mobilephone like", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneNotLike(String value) {
            addCriterion("mobilephone not like", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneIn(List<String> values) {
            addCriterion("mobilephone in", values, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneNotIn(List<String> values) {
            addCriterion("mobilephone not in", values, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneBetween(String value1, String value2) {
            addCriterion("mobilephone between", value1, value2, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneNotBetween(String value1, String value2) {
            addCriterion("mobilephone not between", value1, value2, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andCertTypeIsNull() {
            addCriterion("cert_type is null");
            return (Criteria) this;
        }

        public Criteria andCertTypeIsNotNull() {
            addCriterion("cert_type is not null");
            return (Criteria) this;
        }

        public Criteria andCertTypeEqualTo(Integer value) {
            addCriterion("cert_type =", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotEqualTo(Integer value) {
            addCriterion("cert_type <>", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeGreaterThan(Integer value) {
            addCriterion("cert_type >", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("cert_type >=", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeLessThan(Integer value) {
            addCriterion("cert_type <", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeLessThanOrEqualTo(Integer value) {
            addCriterion("cert_type <=", value, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeIn(List<Integer> values) {
            addCriterion("cert_type in", values, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotIn(List<Integer> values) {
            addCriterion("cert_type not in", values, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeBetween(Integer value1, Integer value2) {
            addCriterion("cert_type between", value1, value2, "certType");
            return (Criteria) this;
        }

        public Criteria andCertTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("cert_type not between", value1, value2, "certType");
            return (Criteria) this;
        }

        public Criteria andCertNoIsNull() {
            addCriterion("cert_no is null");
            return (Criteria) this;
        }

        public Criteria andCertNoIsNotNull() {
            addCriterion("cert_no is not null");
            return (Criteria) this;
        }

        public Criteria andCertNoEqualTo(String value) {
            addCriterion("cert_no =", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotEqualTo(String value) {
            addCriterion("cert_no <>", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoGreaterThan(String value) {
            addCriterion("cert_no >", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoGreaterThanOrEqualTo(String value) {
            addCriterion("cert_no >=", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoLessThan(String value) {
            addCriterion("cert_no <", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoLessThanOrEqualTo(String value) {
            addCriterion("cert_no <=", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoLike(String value) {
            addCriterion("cert_no like", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotLike(String value) {
            addCriterion("cert_no not like", value, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoIn(List<String> values) {
            addCriterion("cert_no in", values, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotIn(List<String> values) {
            addCriterion("cert_no not in", values, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoBetween(String value1, String value2) {
            addCriterion("cert_no between", value1, value2, "certNo");
            return (Criteria) this;
        }

        public Criteria andCertNoNotBetween(String value1, String value2) {
            addCriterion("cert_no not between", value1, value2, "certNo");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdIsNull() {
            addCriterion("pay_transaction_id is null");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdIsNotNull() {
            addCriterion("pay_transaction_id is not null");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdEqualTo(String value) {
            addCriterion("pay_transaction_id =", value, "payTransactionId");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdNotEqualTo(String value) {
            addCriterion("pay_transaction_id <>", value, "payTransactionId");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdGreaterThan(String value) {
            addCriterion("pay_transaction_id >", value, "payTransactionId");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdGreaterThanOrEqualTo(String value) {
            addCriterion("pay_transaction_id >=", value, "payTransactionId");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdLessThan(String value) {
            addCriterion("pay_transaction_id <", value, "payTransactionId");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdLessThanOrEqualTo(String value) {
            addCriterion("pay_transaction_id <=", value, "payTransactionId");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdLike(String value) {
            addCriterion("pay_transaction_id like", value, "payTransactionId");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdNotLike(String value) {
            addCriterion("pay_transaction_id not like", value, "payTransactionId");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdIn(List<String> values) {
            addCriterion("pay_transaction_id in", values, "payTransactionId");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdNotIn(List<String> values) {
            addCriterion("pay_transaction_id not in", values, "payTransactionId");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdBetween(String value1, String value2) {
            addCriterion("pay_transaction_id between", value1, value2, "payTransactionId");
            return (Criteria) this;
        }

        public Criteria andPayTransactionIdNotBetween(String value1, String value2) {
            addCriterion("pay_transaction_id not between", value1, value2, "payTransactionId");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("stat is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("stat is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(Integer value) {
            addCriterion("stat =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(Integer value) {
            addCriterion("stat <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(Integer value) {
            addCriterion("stat >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("stat >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(Integer value) {
            addCriterion("stat <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(Integer value) {
            addCriterion("stat <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<Integer> values) {
            addCriterion("stat in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<Integer> values) {
            addCriterion("stat not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(Integer value1, Integer value2) {
            addCriterion("stat between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(Integer value1, Integer value2) {
            addCriterion("stat not between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andWechatIdIsNull() {
            addCriterion("wechat_id is null");
            return (Criteria) this;
        }

        public Criteria andWechatIdIsNotNull() {
            addCriterion("wechat_id is not null");
            return (Criteria) this;
        }

        public Criteria andWechatIdEqualTo(String value) {
            addCriterion("wechat_id =", value, "wechatId");
            return (Criteria) this;
        }

        public Criteria andWechatIdNotEqualTo(String value) {
            addCriterion("wechat_id <>", value, "wechatId");
            return (Criteria) this;
        }

        public Criteria andWechatIdGreaterThan(String value) {
            addCriterion("wechat_id >", value, "wechatId");
            return (Criteria) this;
        }

        public Criteria andWechatIdGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_id >=", value, "wechatId");
            return (Criteria) this;
        }

        public Criteria andWechatIdLessThan(String value) {
            addCriterion("wechat_id <", value, "wechatId");
            return (Criteria) this;
        }

        public Criteria andWechatIdLessThanOrEqualTo(String value) {
            addCriterion("wechat_id <=", value, "wechatId");
            return (Criteria) this;
        }

        public Criteria andWechatIdLike(String value) {
            addCriterion("wechat_id like", value, "wechatId");
            return (Criteria) this;
        }

        public Criteria andWechatIdNotLike(String value) {
            addCriterion("wechat_id not like", value, "wechatId");
            return (Criteria) this;
        }

        public Criteria andWechatIdIn(List<String> values) {
            addCriterion("wechat_id in", values, "wechatId");
            return (Criteria) this;
        }

        public Criteria andWechatIdNotIn(List<String> values) {
            addCriterion("wechat_id not in", values, "wechatId");
            return (Criteria) this;
        }

        public Criteria andWechatIdBetween(String value1, String value2) {
            addCriterion("wechat_id between", value1, value2, "wechatId");
            return (Criteria) this;
        }

        public Criteria andWechatIdNotBetween(String value1, String value2) {
            addCriterion("wechat_id not between", value1, value2, "wechatId");
            return (Criteria) this;
        }

        public Criteria andOpenIdIsNull() {
            addCriterion("open_id is null");
            return (Criteria) this;
        }

        public Criteria andOpenIdIsNotNull() {
            addCriterion("open_id is not null");
            return (Criteria) this;
        }

        public Criteria andOpenIdEqualTo(String value) {
            addCriterion("open_id =", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotEqualTo(String value) {
            addCriterion("open_id <>", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdGreaterThan(String value) {
            addCriterion("open_id >", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdGreaterThanOrEqualTo(String value) {
            addCriterion("open_id >=", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLessThan(String value) {
            addCriterion("open_id <", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLessThanOrEqualTo(String value) {
            addCriterion("open_id <=", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLike(String value) {
            addCriterion("open_id like", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotLike(String value) {
            addCriterion("open_id not like", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdIn(List<String> values) {
            addCriterion("open_id in", values, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotIn(List<String> values) {
            addCriterion("open_id not in", values, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdBetween(String value1, String value2) {
            addCriterion("open_id between", value1, value2, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotBetween(String value1, String value2) {
            addCriterion("open_id not between", value1, value2, "openId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 12 17:22:54 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_
     *
     * @mbggenerated Tue Apr 12 17:22:54 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}