package com.cuize.task.dao.order.mapper;

import com.cuize.task.dao.order.domain.OrderOptlog;
import com.cuize.task.dao.order.domain.OrderOptlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderOptlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_optlog
     *
     * @mbggenerated Wed Apr 13 15:29:36 CST 2016
     */
    int countByExample(OrderOptlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_optlog
     *
     * @mbggenerated Wed Apr 13 15:29:36 CST 2016
     */
    int deleteByExample(OrderOptlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_optlog
     *
     * @mbggenerated Wed Apr 13 15:29:36 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_optlog
     *
     * @mbggenerated Wed Apr 13 15:29:36 CST 2016
     */
    int insert(OrderOptlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_optlog
     *
     * @mbggenerated Wed Apr 13 15:29:36 CST 2016
     */
    int insertSelective(OrderOptlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_optlog
     *
     * @mbggenerated Wed Apr 13 15:29:36 CST 2016
     */
    List<OrderOptlog> selectByExample(OrderOptlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_optlog
     *
     * @mbggenerated Wed Apr 13 15:29:36 CST 2016
     */
    OrderOptlog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_optlog
     *
     * @mbggenerated Wed Apr 13 15:29:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") OrderOptlog record, @Param("example") OrderOptlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_optlog
     *
     * @mbggenerated Wed Apr 13 15:29:36 CST 2016
     */
    int updateByExample(@Param("record") OrderOptlog record, @Param("example") OrderOptlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_optlog
     *
     * @mbggenerated Wed Apr 13 15:29:36 CST 2016
     */
    int updateByPrimaryKeySelective(OrderOptlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_optlog
     *
     * @mbggenerated Wed Apr 13 15:29:36 CST 2016
     */
    int updateByPrimaryKey(OrderOptlog record);
}