package com.cuize.task.dao.order.mapper;

import com.cuize.task.dao.order.domain.OrderDetailPackdtl;
import com.cuize.task.dao.order.domain.OrderDetailPackdtlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailPackdtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    int countByExample(OrderDetailPackdtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    int deleteByExample(OrderDetailPackdtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    int insert(OrderDetailPackdtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    int insertSelective(OrderDetailPackdtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    List<OrderDetailPackdtl> selectByExample(OrderDetailPackdtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    OrderDetailPackdtl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") OrderDetailPackdtl record, @Param("example") OrderDetailPackdtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    int updateByExample(@Param("record") OrderDetailPackdtl record, @Param("example") OrderDetailPackdtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    int updateByPrimaryKeySelective(OrderDetailPackdtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_packdtl
     *
     * @mbggenerated Thu Apr 21 12:39:41 CST 2016
     */
    int updateByPrimaryKey(OrderDetailPackdtl record);
}