package com.cuize.task.dao.product.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShopExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    public ShopExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIsNull() {
            addCriterion("shopkeeper is null");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIsNotNull() {
            addCriterion("shopkeeper is not null");
            return (Criteria) this;
        }

        public Criteria andShopkeeperEqualTo(String value) {
            addCriterion("shopkeeper =", value, "shopkeeper");
            return (Criteria) this;
        }

        public Criteria andShopkeeperNotEqualTo(String value) {
            addCriterion("shopkeeper <>", value, "shopkeeper");
            return (Criteria) this;
        }

        public Criteria andShopkeeperGreaterThan(String value) {
            addCriterion("shopkeeper >", value, "shopkeeper");
            return (Criteria) this;
        }

        public Criteria andShopkeeperGreaterThanOrEqualTo(String value) {
            addCriterion("shopkeeper >=", value, "shopkeeper");
            return (Criteria) this;
        }

        public Criteria andShopkeeperLessThan(String value) {
            addCriterion("shopkeeper <", value, "shopkeeper");
            return (Criteria) this;
        }

        public Criteria andShopkeeperLessThanOrEqualTo(String value) {
            addCriterion("shopkeeper <=", value, "shopkeeper");
            return (Criteria) this;
        }

        public Criteria andShopkeeperLike(String value) {
            addCriterion("shopkeeper like", value, "shopkeeper");
            return (Criteria) this;
        }

        public Criteria andShopkeeperNotLike(String value) {
            addCriterion("shopkeeper not like", value, "shopkeeper");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIn(List<String> values) {
            addCriterion("shopkeeper in", values, "shopkeeper");
            return (Criteria) this;
        }

        public Criteria andShopkeeperNotIn(List<String> values) {
            addCriterion("shopkeeper not in", values, "shopkeeper");
            return (Criteria) this;
        }

        public Criteria andShopkeeperBetween(String value1, String value2) {
            addCriterion("shopkeeper between", value1, value2, "shopkeeper");
            return (Criteria) this;
        }

        public Criteria andShopkeeperNotBetween(String value1, String value2) {
            addCriterion("shopkeeper not between", value1, value2, "shopkeeper");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIsNull() {
            addCriterion("business_id is null");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIsNotNull() {
            addCriterion("business_id is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessIdEqualTo(Integer value) {
            addCriterion("business_id =", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotEqualTo(Integer value) {
            addCriterion("business_id <>", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdGreaterThan(Integer value) {
            addCriterion("business_id >", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("business_id >=", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdLessThan(Integer value) {
            addCriterion("business_id <", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdLessThanOrEqualTo(Integer value) {
            addCriterion("business_id <=", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIn(List<Integer> values) {
            addCriterion("business_id in", values, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotIn(List<Integer> values) {
            addCriterion("business_id not in", values, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdBetween(Integer value1, Integer value2) {
            addCriterion("business_id between", value1, value2, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotBetween(Integer value1, Integer value2) {
            addCriterion("business_id not between", value1, value2, "businessId");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIdIsNull() {
            addCriterion("shopkeeper_id is null");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIdIsNotNull() {
            addCriterion("shopkeeper_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIdEqualTo(Integer value) {
            addCriterion("shopkeeper_id =", value, "shopkeeperId");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIdNotEqualTo(Integer value) {
            addCriterion("shopkeeper_id <>", value, "shopkeeperId");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIdGreaterThan(Integer value) {
            addCriterion("shopkeeper_id >", value, "shopkeeperId");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopkeeper_id >=", value, "shopkeeperId");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIdLessThan(Integer value) {
            addCriterion("shopkeeper_id <", value, "shopkeeperId");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIdLessThanOrEqualTo(Integer value) {
            addCriterion("shopkeeper_id <=", value, "shopkeeperId");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIdIn(List<Integer> values) {
            addCriterion("shopkeeper_id in", values, "shopkeeperId");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIdNotIn(List<Integer> values) {
            addCriterion("shopkeeper_id not in", values, "shopkeeperId");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIdBetween(Integer value1, Integer value2) {
            addCriterion("shopkeeper_id between", value1, value2, "shopkeeperId");
            return (Criteria) this;
        }

        public Criteria andShopkeeperIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shopkeeper_id not between", value1, value2, "shopkeeperId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andLogoIsNull() {
            addCriterion("logo is null");
            return (Criteria) this;
        }

        public Criteria andLogoIsNotNull() {
            addCriterion("logo is not null");
            return (Criteria) this;
        }

        public Criteria andLogoEqualTo(String value) {
            addCriterion("logo =", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotEqualTo(String value) {
            addCriterion("logo <>", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThan(String value) {
            addCriterion("logo >", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThanOrEqualTo(String value) {
            addCriterion("logo >=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThan(String value) {
            addCriterion("logo <", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThanOrEqualTo(String value) {
            addCriterion("logo <=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLike(String value) {
            addCriterion("logo like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotLike(String value) {
            addCriterion("logo not like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoIn(List<String> values) {
            addCriterion("logo in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotIn(List<String> values) {
            addCriterion("logo not in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoBetween(String value1, String value2) {
            addCriterion("logo between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotBetween(String value1, String value2) {
            addCriterion("logo not between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andPicUrlIsNull() {
            addCriterion("pic_url is null");
            return (Criteria) this;
        }

        public Criteria andPicUrlIsNotNull() {
            addCriterion("pic_url is not null");
            return (Criteria) this;
        }

        public Criteria andPicUrlEqualTo(String value) {
            addCriterion("pic_url =", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotEqualTo(String value) {
            addCriterion("pic_url <>", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlGreaterThan(String value) {
            addCriterion("pic_url >", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("pic_url >=", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLessThan(String value) {
            addCriterion("pic_url <", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLessThanOrEqualTo(String value) {
            addCriterion("pic_url <=", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLike(String value) {
            addCriterion("pic_url like", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotLike(String value) {
            addCriterion("pic_url not like", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlIn(List<String> values) {
            addCriterion("pic_url in", values, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotIn(List<String> values) {
            addCriterion("pic_url not in", values, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlBetween(String value1, String value2) {
            addCriterion("pic_url between", value1, value2, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotBetween(String value1, String value2) {
            addCriterion("pic_url not between", value1, value2, "picUrl");
            return (Criteria) this;
        }

        public Criteria andQrCodeIsNull() {
            addCriterion("qr_code is null");
            return (Criteria) this;
        }

        public Criteria andQrCodeIsNotNull() {
            addCriterion("qr_code is not null");
            return (Criteria) this;
        }

        public Criteria andQrCodeEqualTo(String value) {
            addCriterion("qr_code =", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeNotEqualTo(String value) {
            addCriterion("qr_code <>", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeGreaterThan(String value) {
            addCriterion("qr_code >", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("qr_code >=", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeLessThan(String value) {
            addCriterion("qr_code <", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeLessThanOrEqualTo(String value) {
            addCriterion("qr_code <=", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeLike(String value) {
            addCriterion("qr_code like", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeNotLike(String value) {
            addCriterion("qr_code not like", value, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeIn(List<String> values) {
            addCriterion("qr_code in", values, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeNotIn(List<String> values) {
            addCriterion("qr_code not in", values, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeBetween(String value1, String value2) {
            addCriterion("qr_code between", value1, value2, "qrCode");
            return (Criteria) this;
        }

        public Criteria andQrCodeNotBetween(String value1, String value2) {
            addCriterion("qr_code not between", value1, value2, "qrCode");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsHotIsNull() {
            addCriterion("is_hot is null");
            return (Criteria) this;
        }

        public Criteria andIsHotIsNotNull() {
            addCriterion("is_hot is not null");
            return (Criteria) this;
        }

        public Criteria andIsHotEqualTo(Integer value) {
            addCriterion("is_hot =", value, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotNotEqualTo(Integer value) {
            addCriterion("is_hot <>", value, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotGreaterThan(Integer value) {
            addCriterion("is_hot >", value, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_hot >=", value, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotLessThan(Integer value) {
            addCriterion("is_hot <", value, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotLessThanOrEqualTo(Integer value) {
            addCriterion("is_hot <=", value, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotIn(List<Integer> values) {
            addCriterion("is_hot in", values, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotNotIn(List<Integer> values) {
            addCriterion("is_hot not in", values, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotBetween(Integer value1, Integer value2) {
            addCriterion("is_hot between", value1, value2, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotNotBetween(Integer value1, Integer value2) {
            addCriterion("is_hot not between", value1, value2, "isHot");
            return (Criteria) this;
        }

        public Criteria andFlagShipIsNull() {
            addCriterion("flag_ship is null");
            return (Criteria) this;
        }

        public Criteria andFlagShipIsNotNull() {
            addCriterion("flag_ship is not null");
            return (Criteria) this;
        }

        public Criteria andFlagShipEqualTo(Integer value) {
            addCriterion("flag_ship =", value, "flagShip");
            return (Criteria) this;
        }

        public Criteria andFlagShipNotEqualTo(Integer value) {
            addCriterion("flag_ship <>", value, "flagShip");
            return (Criteria) this;
        }

        public Criteria andFlagShipGreaterThan(Integer value) {
            addCriterion("flag_ship >", value, "flagShip");
            return (Criteria) this;
        }

        public Criteria andFlagShipGreaterThanOrEqualTo(Integer value) {
            addCriterion("flag_ship >=", value, "flagShip");
            return (Criteria) this;
        }

        public Criteria andFlagShipLessThan(Integer value) {
            addCriterion("flag_ship <", value, "flagShip");
            return (Criteria) this;
        }

        public Criteria andFlagShipLessThanOrEqualTo(Integer value) {
            addCriterion("flag_ship <=", value, "flagShip");
            return (Criteria) this;
        }

        public Criteria andFlagShipIn(List<Integer> values) {
            addCriterion("flag_ship in", values, "flagShip");
            return (Criteria) this;
        }

        public Criteria andFlagShipNotIn(List<Integer> values) {
            addCriterion("flag_ship not in", values, "flagShip");
            return (Criteria) this;
        }

        public Criteria andFlagShipBetween(Integer value1, Integer value2) {
            addCriterion("flag_ship between", value1, value2, "flagShip");
            return (Criteria) this;
        }

        public Criteria andFlagShipNotBetween(Integer value1, Integer value2) {
            addCriterion("flag_ship not between", value1, value2, "flagShip");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginIsNull() {
            addCriterion("office_begin is null");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginIsNotNull() {
            addCriterion("office_begin is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginEqualTo(String value) {
            addCriterion("office_begin =", value, "officeBegin");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginNotEqualTo(String value) {
            addCriterion("office_begin <>", value, "officeBegin");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginGreaterThan(String value) {
            addCriterion("office_begin >", value, "officeBegin");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginGreaterThanOrEqualTo(String value) {
            addCriterion("office_begin >=", value, "officeBegin");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginLessThan(String value) {
            addCriterion("office_begin <", value, "officeBegin");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginLessThanOrEqualTo(String value) {
            addCriterion("office_begin <=", value, "officeBegin");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginLike(String value) {
            addCriterion("office_begin like", value, "officeBegin");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginNotLike(String value) {
            addCriterion("office_begin not like", value, "officeBegin");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginIn(List<String> values) {
            addCriterion("office_begin in", values, "officeBegin");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginNotIn(List<String> values) {
            addCriterion("office_begin not in", values, "officeBegin");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginBetween(String value1, String value2) {
            addCriterion("office_begin between", value1, value2, "officeBegin");
            return (Criteria) this;
        }

        public Criteria andOfficeBeginNotBetween(String value1, String value2) {
            addCriterion("office_begin not between", value1, value2, "officeBegin");
            return (Criteria) this;
        }

        public Criteria andOfficeEndIsNull() {
            addCriterion("office_end is null");
            return (Criteria) this;
        }

        public Criteria andOfficeEndIsNotNull() {
            addCriterion("office_end is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeEndEqualTo(String value) {
            addCriterion("office_end =", value, "officeEnd");
            return (Criteria) this;
        }

        public Criteria andOfficeEndNotEqualTo(String value) {
            addCriterion("office_end <>", value, "officeEnd");
            return (Criteria) this;
        }

        public Criteria andOfficeEndGreaterThan(String value) {
            addCriterion("office_end >", value, "officeEnd");
            return (Criteria) this;
        }

        public Criteria andOfficeEndGreaterThanOrEqualTo(String value) {
            addCriterion("office_end >=", value, "officeEnd");
            return (Criteria) this;
        }

        public Criteria andOfficeEndLessThan(String value) {
            addCriterion("office_end <", value, "officeEnd");
            return (Criteria) this;
        }

        public Criteria andOfficeEndLessThanOrEqualTo(String value) {
            addCriterion("office_end <=", value, "officeEnd");
            return (Criteria) this;
        }

        public Criteria andOfficeEndLike(String value) {
            addCriterion("office_end like", value, "officeEnd");
            return (Criteria) this;
        }

        public Criteria andOfficeEndNotLike(String value) {
            addCriterion("office_end not like", value, "officeEnd");
            return (Criteria) this;
        }

        public Criteria andOfficeEndIn(List<String> values) {
            addCriterion("office_end in", values, "officeEnd");
            return (Criteria) this;
        }

        public Criteria andOfficeEndNotIn(List<String> values) {
            addCriterion("office_end not in", values, "officeEnd");
            return (Criteria) this;
        }

        public Criteria andOfficeEndBetween(String value1, String value2) {
            addCriterion("office_end between", value1, value2, "officeEnd");
            return (Criteria) this;
        }

        public Criteria andOfficeEndNotBetween(String value1, String value2) {
            addCriterion("office_end not between", value1, value2, "officeEnd");
            return (Criteria) this;
        }

        public Criteria andMainCategoryIsNull() {
            addCriterion("main_category is null");
            return (Criteria) this;
        }

        public Criteria andMainCategoryIsNotNull() {
            addCriterion("main_category is not null");
            return (Criteria) this;
        }

        public Criteria andMainCategoryEqualTo(Integer value) {
            addCriterion("main_category =", value, "mainCategory");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNotEqualTo(Integer value) {
            addCriterion("main_category <>", value, "mainCategory");
            return (Criteria) this;
        }

        public Criteria andMainCategoryGreaterThan(Integer value) {
            addCriterion("main_category >", value, "mainCategory");
            return (Criteria) this;
        }

        public Criteria andMainCategoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("main_category >=", value, "mainCategory");
            return (Criteria) this;
        }

        public Criteria andMainCategoryLessThan(Integer value) {
            addCriterion("main_category <", value, "mainCategory");
            return (Criteria) this;
        }

        public Criteria andMainCategoryLessThanOrEqualTo(Integer value) {
            addCriterion("main_category <=", value, "mainCategory");
            return (Criteria) this;
        }

        public Criteria andMainCategoryIn(List<Integer> values) {
            addCriterion("main_category in", values, "mainCategory");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNotIn(List<Integer> values) {
            addCriterion("main_category not in", values, "mainCategory");
            return (Criteria) this;
        }

        public Criteria andMainCategoryBetween(Integer value1, Integer value2) {
            addCriterion("main_category between", value1, value2, "mainCategory");
            return (Criteria) this;
        }

        public Criteria andMainCategoryNotBetween(Integer value1, Integer value2) {
            addCriterion("main_category not between", value1, value2, "mainCategory");
            return (Criteria) this;
        }

        public Criteria andKeepNameIsNull() {
            addCriterion("keep_name is null");
            return (Criteria) this;
        }

        public Criteria andKeepNameIsNotNull() {
            addCriterion("keep_name is not null");
            return (Criteria) this;
        }

        public Criteria andKeepNameEqualTo(String value) {
            addCriterion("keep_name =", value, "keepName");
            return (Criteria) this;
        }

        public Criteria andKeepNameNotEqualTo(String value) {
            addCriterion("keep_name <>", value, "keepName");
            return (Criteria) this;
        }

        public Criteria andKeepNameGreaterThan(String value) {
            addCriterion("keep_name >", value, "keepName");
            return (Criteria) this;
        }

        public Criteria andKeepNameGreaterThanOrEqualTo(String value) {
            addCriterion("keep_name >=", value, "keepName");
            return (Criteria) this;
        }

        public Criteria andKeepNameLessThan(String value) {
            addCriterion("keep_name <", value, "keepName");
            return (Criteria) this;
        }

        public Criteria andKeepNameLessThanOrEqualTo(String value) {
            addCriterion("keep_name <=", value, "keepName");
            return (Criteria) this;
        }

        public Criteria andKeepNameLike(String value) {
            addCriterion("keep_name like", value, "keepName");
            return (Criteria) this;
        }

        public Criteria andKeepNameNotLike(String value) {
            addCriterion("keep_name not like", value, "keepName");
            return (Criteria) this;
        }

        public Criteria andKeepNameIn(List<String> values) {
            addCriterion("keep_name in", values, "keepName");
            return (Criteria) this;
        }

        public Criteria andKeepNameNotIn(List<String> values) {
            addCriterion("keep_name not in", values, "keepName");
            return (Criteria) this;
        }

        public Criteria andKeepNameBetween(String value1, String value2) {
            addCriterion("keep_name between", value1, value2, "keepName");
            return (Criteria) this;
        }

        public Criteria andKeepNameNotBetween(String value1, String value2) {
            addCriterion("keep_name not between", value1, value2, "keepName");
            return (Criteria) this;
        }

        public Criteria andXAxisIsNull() {
            addCriterion("x_axis is null");
            return (Criteria) this;
        }

        public Criteria andXAxisIsNotNull() {
            addCriterion("x_axis is not null");
            return (Criteria) this;
        }

        public Criteria andXAxisEqualTo(Integer value) {
            addCriterion("x_axis =", value, "xAxis");
            return (Criteria) this;
        }

        public Criteria andXAxisNotEqualTo(Integer value) {
            addCriterion("x_axis <>", value, "xAxis");
            return (Criteria) this;
        }

        public Criteria andXAxisGreaterThan(Integer value) {
            addCriterion("x_axis >", value, "xAxis");
            return (Criteria) this;
        }

        public Criteria andXAxisGreaterThanOrEqualTo(Integer value) {
            addCriterion("x_axis >=", value, "xAxis");
            return (Criteria) this;
        }

        public Criteria andXAxisLessThan(Integer value) {
            addCriterion("x_axis <", value, "xAxis");
            return (Criteria) this;
        }

        public Criteria andXAxisLessThanOrEqualTo(Integer value) {
            addCriterion("x_axis <=", value, "xAxis");
            return (Criteria) this;
        }

        public Criteria andXAxisIn(List<Integer> values) {
            addCriterion("x_axis in", values, "xAxis");
            return (Criteria) this;
        }

        public Criteria andXAxisNotIn(List<Integer> values) {
            addCriterion("x_axis not in", values, "xAxis");
            return (Criteria) this;
        }

        public Criteria andXAxisBetween(Integer value1, Integer value2) {
            addCriterion("x_axis between", value1, value2, "xAxis");
            return (Criteria) this;
        }

        public Criteria andXAxisNotBetween(Integer value1, Integer value2) {
            addCriterion("x_axis not between", value1, value2, "xAxis");
            return (Criteria) this;
        }

        public Criteria andYAxisIsNull() {
            addCriterion("y_axis is null");
            return (Criteria) this;
        }

        public Criteria andYAxisIsNotNull() {
            addCriterion("y_axis is not null");
            return (Criteria) this;
        }

        public Criteria andYAxisEqualTo(Integer value) {
            addCriterion("y_axis =", value, "yAxis");
            return (Criteria) this;
        }

        public Criteria andYAxisNotEqualTo(Integer value) {
            addCriterion("y_axis <>", value, "yAxis");
            return (Criteria) this;
        }

        public Criteria andYAxisGreaterThan(Integer value) {
            addCriterion("y_axis >", value, "yAxis");
            return (Criteria) this;
        }

        public Criteria andYAxisGreaterThanOrEqualTo(Integer value) {
            addCriterion("y_axis >=", value, "yAxis");
            return (Criteria) this;
        }

        public Criteria andYAxisLessThan(Integer value) {
            addCriterion("y_axis <", value, "yAxis");
            return (Criteria) this;
        }

        public Criteria andYAxisLessThanOrEqualTo(Integer value) {
            addCriterion("y_axis <=", value, "yAxis");
            return (Criteria) this;
        }

        public Criteria andYAxisIn(List<Integer> values) {
            addCriterion("y_axis in", values, "yAxis");
            return (Criteria) this;
        }

        public Criteria andYAxisNotIn(List<Integer> values) {
            addCriterion("y_axis not in", values, "yAxis");
            return (Criteria) this;
        }

        public Criteria andYAxisBetween(Integer value1, Integer value2) {
            addCriterion("y_axis between", value1, value2, "yAxis");
            return (Criteria) this;
        }

        public Criteria andYAxisNotBetween(Integer value1, Integer value2) {
            addCriterion("y_axis not between", value1, value2, "yAxis");
            return (Criteria) this;
        }

        public Criteria andTelphoneIsNull() {
            addCriterion("telphone is null");
            return (Criteria) this;
        }

        public Criteria andTelphoneIsNotNull() {
            addCriterion("telphone is not null");
            return (Criteria) this;
        }

        public Criteria andTelphoneEqualTo(String value) {
            addCriterion("telphone =", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotEqualTo(String value) {
            addCriterion("telphone <>", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneGreaterThan(String value) {
            addCriterion("telphone >", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneGreaterThanOrEqualTo(String value) {
            addCriterion("telphone >=", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLessThan(String value) {
            addCriterion("telphone <", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLessThanOrEqualTo(String value) {
            addCriterion("telphone <=", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLike(String value) {
            addCriterion("telphone like", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotLike(String value) {
            addCriterion("telphone not like", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneIn(List<String> values) {
            addCriterion("telphone in", values, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotIn(List<String> values) {
            addCriterion("telphone not in", values, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneBetween(String value1, String value2) {
            addCriterion("telphone between", value1, value2, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotBetween(String value1, String value2) {
            addCriterion("telphone not between", value1, value2, "telphone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneIsNull() {
            addCriterion("mobilephone is null");
            return (Criteria) this;
        }

        public Criteria andMobilephoneIsNotNull() {
            addCriterion("mobilephone is not null");
            return (Criteria) this;
        }

        public Criteria andMobilephoneEqualTo(String value) {
            addCriterion("mobilephone =", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneNotEqualTo(String value) {
            addCriterion("mobilephone <>", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneGreaterThan(String value) {
            addCriterion("mobilephone >", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneGreaterThanOrEqualTo(String value) {
            addCriterion("mobilephone >=", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneLessThan(String value) {
            addCriterion("mobilephone <", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneLessThanOrEqualTo(String value) {
            addCriterion("mobilephone <=", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneLike(String value) {
            addCriterion("mobilephone like", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneNotLike(String value) {
            addCriterion("mobilephone not like", value, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneIn(List<String> values) {
            addCriterion("mobilephone in", values, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneNotIn(List<String> values) {
            addCriterion("mobilephone not in", values, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneBetween(String value1, String value2) {
            addCriterion("mobilephone between", value1, value2, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andMobilephoneNotBetween(String value1, String value2) {
            addCriterion("mobilephone not between", value1, value2, "mobilephone");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andViewIsNull() {
            addCriterion("view is null");
            return (Criteria) this;
        }

        public Criteria andViewIsNotNull() {
            addCriterion("view is not null");
            return (Criteria) this;
        }

        public Criteria andViewEqualTo(Integer value) {
            addCriterion("view =", value, "view");
            return (Criteria) this;
        }

        public Criteria andViewNotEqualTo(Integer value) {
            addCriterion("view <>", value, "view");
            return (Criteria) this;
        }

        public Criteria andViewGreaterThan(Integer value) {
            addCriterion("view >", value, "view");
            return (Criteria) this;
        }

        public Criteria andViewGreaterThanOrEqualTo(Integer value) {
            addCriterion("view >=", value, "view");
            return (Criteria) this;
        }

        public Criteria andViewLessThan(Integer value) {
            addCriterion("view <", value, "view");
            return (Criteria) this;
        }

        public Criteria andViewLessThanOrEqualTo(Integer value) {
            addCriterion("view <=", value, "view");
            return (Criteria) this;
        }

        public Criteria andViewIn(List<Integer> values) {
            addCriterion("view in", values, "view");
            return (Criteria) this;
        }

        public Criteria andViewNotIn(List<Integer> values) {
            addCriterion("view not in", values, "view");
            return (Criteria) this;
        }

        public Criteria andViewBetween(Integer value1, Integer value2) {
            addCriterion("view between", value1, value2, "view");
            return (Criteria) this;
        }

        public Criteria andViewNotBetween(Integer value1, Integer value2) {
            addCriterion("view not between", value1, value2, "view");
            return (Criteria) this;
        }

        public Criteria andTemplshopidIsNull() {
            addCriterion("templshopid is null");
            return (Criteria) this;
        }

        public Criteria andTemplshopidIsNotNull() {
            addCriterion("templshopid is not null");
            return (Criteria) this;
        }

        public Criteria andTemplshopidEqualTo(Integer value) {
            addCriterion("templshopid =", value, "templshopid");
            return (Criteria) this;
        }

        public Criteria andTemplshopidNotEqualTo(Integer value) {
            addCriterion("templshopid <>", value, "templshopid");
            return (Criteria) this;
        }

        public Criteria andTemplshopidGreaterThan(Integer value) {
            addCriterion("templshopid >", value, "templshopid");
            return (Criteria) this;
        }

        public Criteria andTemplshopidGreaterThanOrEqualTo(Integer value) {
            addCriterion("templshopid >=", value, "templshopid");
            return (Criteria) this;
        }

        public Criteria andTemplshopidLessThan(Integer value) {
            addCriterion("templshopid <", value, "templshopid");
            return (Criteria) this;
        }

        public Criteria andTemplshopidLessThanOrEqualTo(Integer value) {
            addCriterion("templshopid <=", value, "templshopid");
            return (Criteria) this;
        }

        public Criteria andTemplshopidIn(List<Integer> values) {
            addCriterion("templshopid in", values, "templshopid");
            return (Criteria) this;
        }

        public Criteria andTemplshopidNotIn(List<Integer> values) {
            addCriterion("templshopid not in", values, "templshopid");
            return (Criteria) this;
        }

        public Criteria andTemplshopidBetween(Integer value1, Integer value2) {
            addCriterion("templshopid between", value1, value2, "templshopid");
            return (Criteria) this;
        }

        public Criteria andTemplshopidNotBetween(Integer value1, Integer value2) {
            addCriterion("templshopid not between", value1, value2, "templshopid");
            return (Criteria) this;
        }

        public Criteria andEmailstatueIsNull() {
            addCriterion("emailstatue is null");
            return (Criteria) this;
        }

        public Criteria andEmailstatueIsNotNull() {
            addCriterion("emailstatue is not null");
            return (Criteria) this;
        }

        public Criteria andEmailstatueEqualTo(Integer value) {
            addCriterion("emailstatue =", value, "emailstatue");
            return (Criteria) this;
        }

        public Criteria andEmailstatueNotEqualTo(Integer value) {
            addCriterion("emailstatue <>", value, "emailstatue");
            return (Criteria) this;
        }

        public Criteria andEmailstatueGreaterThan(Integer value) {
            addCriterion("emailstatue >", value, "emailstatue");
            return (Criteria) this;
        }

        public Criteria andEmailstatueGreaterThanOrEqualTo(Integer value) {
            addCriterion("emailstatue >=", value, "emailstatue");
            return (Criteria) this;
        }

        public Criteria andEmailstatueLessThan(Integer value) {
            addCriterion("emailstatue <", value, "emailstatue");
            return (Criteria) this;
        }

        public Criteria andEmailstatueLessThanOrEqualTo(Integer value) {
            addCriterion("emailstatue <=", value, "emailstatue");
            return (Criteria) this;
        }

        public Criteria andEmailstatueIn(List<Integer> values) {
            addCriterion("emailstatue in", values, "emailstatue");
            return (Criteria) this;
        }

        public Criteria andEmailstatueNotIn(List<Integer> values) {
            addCriterion("emailstatue not in", values, "emailstatue");
            return (Criteria) this;
        }

        public Criteria andEmailstatueBetween(Integer value1, Integer value2) {
            addCriterion("emailstatue between", value1, value2, "emailstatue");
            return (Criteria) this;
        }

        public Criteria andEmailstatueNotBetween(Integer value1, Integer value2) {
            addCriterion("emailstatue not between", value1, value2, "emailstatue");
            return (Criteria) this;
        }

        public Criteria andUsageIsNull() {
            addCriterion("usage_ is null");
            return (Criteria) this;
        }

        public Criteria andUsageIsNotNull() {
            addCriterion("usage_ is not null");
            return (Criteria) this;
        }

        public Criteria andUsageEqualTo(String value) {
            addCriterion("usage_ =", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageNotEqualTo(String value) {
            addCriterion("usage_ <>", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageGreaterThan(String value) {
            addCriterion("usage_ >", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageGreaterThanOrEqualTo(String value) {
            addCriterion("usage_ >=", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageLessThan(String value) {
            addCriterion("usage_ <", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageLessThanOrEqualTo(String value) {
            addCriterion("usage_ <=", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageLike(String value) {
            addCriterion("usage_ like", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageNotLike(String value) {
            addCriterion("usage_ not like", value, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageIn(List<String> values) {
            addCriterion("usage_ in", values, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageNotIn(List<String> values) {
            addCriterion("usage_ not in", values, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageBetween(String value1, String value2) {
            addCriterion("usage_ between", value1, value2, "usage");
            return (Criteria) this;
        }

        public Criteria andUsageNotBetween(String value1, String value2) {
            addCriterion("usage_ not between", value1, value2, "usage");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category_ is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category_ is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category_ =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category_ <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category_ >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category_ >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category_ <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category_ <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category_ like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category_ not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category_ in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category_ not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category_ between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category_ not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andPersonPerpriceIsNull() {
            addCriterion("person_perprice is null");
            return (Criteria) this;
        }

        public Criteria andPersonPerpriceIsNotNull() {
            addCriterion("person_perprice is not null");
            return (Criteria) this;
        }

        public Criteria andPersonPerpriceEqualTo(Integer value) {
            addCriterion("person_perprice =", value, "personPerprice");
            return (Criteria) this;
        }

        public Criteria andPersonPerpriceNotEqualTo(Integer value) {
            addCriterion("person_perprice <>", value, "personPerprice");
            return (Criteria) this;
        }

        public Criteria andPersonPerpriceGreaterThan(Integer value) {
            addCriterion("person_perprice >", value, "personPerprice");
            return (Criteria) this;
        }

        public Criteria andPersonPerpriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("person_perprice >=", value, "personPerprice");
            return (Criteria) this;
        }

        public Criteria andPersonPerpriceLessThan(Integer value) {
            addCriterion("person_perprice <", value, "personPerprice");
            return (Criteria) this;
        }

        public Criteria andPersonPerpriceLessThanOrEqualTo(Integer value) {
            addCriterion("person_perprice <=", value, "personPerprice");
            return (Criteria) this;
        }

        public Criteria andPersonPerpriceIn(List<Integer> values) {
            addCriterion("person_perprice in", values, "personPerprice");
            return (Criteria) this;
        }

        public Criteria andPersonPerpriceNotIn(List<Integer> values) {
            addCriterion("person_perprice not in", values, "personPerprice");
            return (Criteria) this;
        }

        public Criteria andPersonPerpriceBetween(Integer value1, Integer value2) {
            addCriterion("person_perprice between", value1, value2, "personPerprice");
            return (Criteria) this;
        }

        public Criteria andPersonPerpriceNotBetween(Integer value1, Integer value2) {
            addCriterion("person_perprice not between", value1, value2, "personPerprice");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeIsNull() {
            addCriterion("schedule_notice is null");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeIsNotNull() {
            addCriterion("schedule_notice is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeEqualTo(String value) {
            addCriterion("schedule_notice =", value, "scheduleNotice");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeNotEqualTo(String value) {
            addCriterion("schedule_notice <>", value, "scheduleNotice");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeGreaterThan(String value) {
            addCriterion("schedule_notice >", value, "scheduleNotice");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeGreaterThanOrEqualTo(String value) {
            addCriterion("schedule_notice >=", value, "scheduleNotice");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeLessThan(String value) {
            addCriterion("schedule_notice <", value, "scheduleNotice");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeLessThanOrEqualTo(String value) {
            addCriterion("schedule_notice <=", value, "scheduleNotice");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeLike(String value) {
            addCriterion("schedule_notice like", value, "scheduleNotice");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeNotLike(String value) {
            addCriterion("schedule_notice not like", value, "scheduleNotice");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeIn(List<String> values) {
            addCriterion("schedule_notice in", values, "scheduleNotice");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeNotIn(List<String> values) {
            addCriterion("schedule_notice not in", values, "scheduleNotice");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeBetween(String value1, String value2) {
            addCriterion("schedule_notice between", value1, value2, "scheduleNotice");
            return (Criteria) this;
        }

        public Criteria andScheduleNoticeNotBetween(String value1, String value2) {
            addCriterion("schedule_notice not between", value1, value2, "scheduleNotice");
            return (Criteria) this;
        }

        public Criteria andServiceChargeIsNull() {
            addCriterion("service_charge is null");
            return (Criteria) this;
        }

        public Criteria andServiceChargeIsNotNull() {
            addCriterion("service_charge is not null");
            return (Criteria) this;
        }

        public Criteria andServiceChargeEqualTo(Double value) {
            addCriterion("service_charge =", value, "serviceCharge");
            return (Criteria) this;
        }

        public Criteria andServiceChargeNotEqualTo(Double value) {
            addCriterion("service_charge <>", value, "serviceCharge");
            return (Criteria) this;
        }

        public Criteria andServiceChargeGreaterThan(Double value) {
            addCriterion("service_charge >", value, "serviceCharge");
            return (Criteria) this;
        }

        public Criteria andServiceChargeGreaterThanOrEqualTo(Double value) {
            addCriterion("service_charge >=", value, "serviceCharge");
            return (Criteria) this;
        }

        public Criteria andServiceChargeLessThan(Double value) {
            addCriterion("service_charge <", value, "serviceCharge");
            return (Criteria) this;
        }

        public Criteria andServiceChargeLessThanOrEqualTo(Double value) {
            addCriterion("service_charge <=", value, "serviceCharge");
            return (Criteria) this;
        }

        public Criteria andServiceChargeIn(List<Double> values) {
            addCriterion("service_charge in", values, "serviceCharge");
            return (Criteria) this;
        }

        public Criteria andServiceChargeNotIn(List<Double> values) {
            addCriterion("service_charge not in", values, "serviceCharge");
            return (Criteria) this;
        }

        public Criteria andServiceChargeBetween(Double value1, Double value2) {
            addCriterion("service_charge between", value1, value2, "serviceCharge");
            return (Criteria) this;
        }

        public Criteria andServiceChargeNotBetween(Double value1, Double value2) {
            addCriterion("service_charge not between", value1, value2, "serviceCharge");
            return (Criteria) this;
        }

        public Criteria andIsFreeIsNull() {
            addCriterion("is_free is null");
            return (Criteria) this;
        }

        public Criteria andIsFreeIsNotNull() {
            addCriterion("is_free is not null");
            return (Criteria) this;
        }

        public Criteria andIsFreeEqualTo(Integer value) {
            addCriterion("is_free =", value, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeNotEqualTo(Integer value) {
            addCriterion("is_free <>", value, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeGreaterThan(Integer value) {
            addCriterion("is_free >", value, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_free >=", value, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeLessThan(Integer value) {
            addCriterion("is_free <", value, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeLessThanOrEqualTo(Integer value) {
            addCriterion("is_free <=", value, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeIn(List<Integer> values) {
            addCriterion("is_free in", values, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeNotIn(List<Integer> values) {
            addCriterion("is_free not in", values, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeBetween(Integer value1, Integer value2) {
            addCriterion("is_free between", value1, value2, "isFree");
            return (Criteria) this;
        }

        public Criteria andIsFreeNotBetween(Integer value1, Integer value2) {
            addCriterion("is_free not between", value1, value2, "isFree");
            return (Criteria) this;
        }

        public Criteria andAdvertisementIsNull() {
            addCriterion("advertisement is null");
            return (Criteria) this;
        }

        public Criteria andAdvertisementIsNotNull() {
            addCriterion("advertisement is not null");
            return (Criteria) this;
        }

        public Criteria andAdvertisementEqualTo(String value) {
            addCriterion("advertisement =", value, "advertisement");
            return (Criteria) this;
        }

        public Criteria andAdvertisementNotEqualTo(String value) {
            addCriterion("advertisement <>", value, "advertisement");
            return (Criteria) this;
        }

        public Criteria andAdvertisementGreaterThan(String value) {
            addCriterion("advertisement >", value, "advertisement");
            return (Criteria) this;
        }

        public Criteria andAdvertisementGreaterThanOrEqualTo(String value) {
            addCriterion("advertisement >=", value, "advertisement");
            return (Criteria) this;
        }

        public Criteria andAdvertisementLessThan(String value) {
            addCriterion("advertisement <", value, "advertisement");
            return (Criteria) this;
        }

        public Criteria andAdvertisementLessThanOrEqualTo(String value) {
            addCriterion("advertisement <=", value, "advertisement");
            return (Criteria) this;
        }

        public Criteria andAdvertisementLike(String value) {
            addCriterion("advertisement like", value, "advertisement");
            return (Criteria) this;
        }

        public Criteria andAdvertisementNotLike(String value) {
            addCriterion("advertisement not like", value, "advertisement");
            return (Criteria) this;
        }

        public Criteria andAdvertisementIn(List<String> values) {
            addCriterion("advertisement in", values, "advertisement");
            return (Criteria) this;
        }

        public Criteria andAdvertisementNotIn(List<String> values) {
            addCriterion("advertisement not in", values, "advertisement");
            return (Criteria) this;
        }

        public Criteria andAdvertisementBetween(String value1, String value2) {
            addCriterion("advertisement between", value1, value2, "advertisement");
            return (Criteria) this;
        }

        public Criteria andAdvertisementNotBetween(String value1, String value2) {
            addCriterion("advertisement not between", value1, value2, "advertisement");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentIsNull() {
            addCriterion("delivery_commitment is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentIsNotNull() {
            addCriterion("delivery_commitment is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentEqualTo(String value) {
            addCriterion("delivery_commitment =", value, "deliveryCommitment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentNotEqualTo(String value) {
            addCriterion("delivery_commitment <>", value, "deliveryCommitment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentGreaterThan(String value) {
            addCriterion("delivery_commitment >", value, "deliveryCommitment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentGreaterThanOrEqualTo(String value) {
            addCriterion("delivery_commitment >=", value, "deliveryCommitment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentLessThan(String value) {
            addCriterion("delivery_commitment <", value, "deliveryCommitment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentLessThanOrEqualTo(String value) {
            addCriterion("delivery_commitment <=", value, "deliveryCommitment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentLike(String value) {
            addCriterion("delivery_commitment like", value, "deliveryCommitment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentNotLike(String value) {
            addCriterion("delivery_commitment not like", value, "deliveryCommitment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentIn(List<String> values) {
            addCriterion("delivery_commitment in", values, "deliveryCommitment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentNotIn(List<String> values) {
            addCriterion("delivery_commitment not in", values, "deliveryCommitment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentBetween(String value1, String value2) {
            addCriterion("delivery_commitment between", value1, value2, "deliveryCommitment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommitmentNotBetween(String value1, String value2) {
            addCriterion("delivery_commitment not between", value1, value2, "deliveryCommitment");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Integer value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Integer value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Integer value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Integer value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Integer value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Integer> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Integer> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Integer value1, Integer value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParkAbstractIsNull() {
            addCriterion("park_abstract is null");
            return (Criteria) this;
        }

        public Criteria andParkAbstractIsNotNull() {
            addCriterion("park_abstract is not null");
            return (Criteria) this;
        }

        public Criteria andParkAbstractEqualTo(String value) {
            addCriterion("park_abstract =", value, "parkAbstract");
            return (Criteria) this;
        }

        public Criteria andParkAbstractNotEqualTo(String value) {
            addCriterion("park_abstract <>", value, "parkAbstract");
            return (Criteria) this;
        }

        public Criteria andParkAbstractGreaterThan(String value) {
            addCriterion("park_abstract >", value, "parkAbstract");
            return (Criteria) this;
        }

        public Criteria andParkAbstractGreaterThanOrEqualTo(String value) {
            addCriterion("park_abstract >=", value, "parkAbstract");
            return (Criteria) this;
        }

        public Criteria andParkAbstractLessThan(String value) {
            addCriterion("park_abstract <", value, "parkAbstract");
            return (Criteria) this;
        }

        public Criteria andParkAbstractLessThanOrEqualTo(String value) {
            addCriterion("park_abstract <=", value, "parkAbstract");
            return (Criteria) this;
        }

        public Criteria andParkAbstractLike(String value) {
            addCriterion("park_abstract like", value, "parkAbstract");
            return (Criteria) this;
        }

        public Criteria andParkAbstractNotLike(String value) {
            addCriterion("park_abstract not like", value, "parkAbstract");
            return (Criteria) this;
        }

        public Criteria andParkAbstractIn(List<String> values) {
            addCriterion("park_abstract in", values, "parkAbstract");
            return (Criteria) this;
        }

        public Criteria andParkAbstractNotIn(List<String> values) {
            addCriterion("park_abstract not in", values, "parkAbstract");
            return (Criteria) this;
        }

        public Criteria andParkAbstractBetween(String value1, String value2) {
            addCriterion("park_abstract between", value1, value2, "parkAbstract");
            return (Criteria) this;
        }

        public Criteria andParkAbstractNotBetween(String value1, String value2) {
            addCriterion("park_abstract not between", value1, value2, "parkAbstract");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeIsNull() {
            addCriterion("ticket_systype is null");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeIsNotNull() {
            addCriterion("ticket_systype is not null");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeEqualTo(Integer value) {
            addCriterion("ticket_systype =", value, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeNotEqualTo(Integer value) {
            addCriterion("ticket_systype <>", value, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeGreaterThan(Integer value) {
            addCriterion("ticket_systype >", value, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ticket_systype >=", value, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeLessThan(Integer value) {
            addCriterion("ticket_systype <", value, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeLessThanOrEqualTo(Integer value) {
            addCriterion("ticket_systype <=", value, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeIn(List<Integer> values) {
            addCriterion("ticket_systype in", values, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeNotIn(List<Integer> values) {
            addCriterion("ticket_systype not in", values, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeBetween(Integer value1, Integer value2) {
            addCriterion("ticket_systype between", value1, value2, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andTicketSystypeNotBetween(Integer value1, Integer value2) {
            addCriterion("ticket_systype not between", value1, value2, "ticketSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeIsNull() {
            addCriterion("gate_systype is null");
            return (Criteria) this;
        }

        public Criteria andGateSystypeIsNotNull() {
            addCriterion("gate_systype is not null");
            return (Criteria) this;
        }

        public Criteria andGateSystypeEqualTo(Integer value) {
            addCriterion("gate_systype =", value, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeNotEqualTo(Integer value) {
            addCriterion("gate_systype <>", value, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeGreaterThan(Integer value) {
            addCriterion("gate_systype >", value, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("gate_systype >=", value, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeLessThan(Integer value) {
            addCriterion("gate_systype <", value, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeLessThanOrEqualTo(Integer value) {
            addCriterion("gate_systype <=", value, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeIn(List<Integer> values) {
            addCriterion("gate_systype in", values, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeNotIn(List<Integer> values) {
            addCriterion("gate_systype not in", values, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeBetween(Integer value1, Integer value2) {
            addCriterion("gate_systype between", value1, value2, "gateSystype");
            return (Criteria) this;
        }

        public Criteria andGateSystypeNotBetween(Integer value1, Integer value2) {
            addCriterion("gate_systype not between", value1, value2, "gateSystype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 12 17:44:27 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbggenerated Tue Apr 12 17:44:27 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}